### ISSUE TITLE
Transcription - roman numerals, internal punctuation

### ISSUE THREAD

**Issue by rarebkcat** [rbms-bsc/DCRMR#107]
In DCRMR, do we want to retain or omit the internal punctuation within roman numerals?
 
In Transcription, [0.5.34 Punctuation within roman numerals](https://rbms-bsc.github.io/DCRMR/general-rules/Transcription/#0534-punctuation-within-roman-numerals) calls for internal punctuation within roman numerals to be retained, following the RBMS PS. However, the PPDM chapters calls for punctuation within roman numerals to be omitted, following DCRM(B); see, for example, [4.205.4.1 in Date of Publication](https://rbms-bsc.github.io/DCRMR/ppdm/Date-of-publication/#42054-transcription-involving-adjustments-or-additions). 
 
The only reference we could come up with about the change is in an [analysis document at 1.7.3](https://docs.google.com/document/d/1xkPntKGEAbu3NnuMhDF-z5oWNyVZrbarkY7sL6jFhjw/edit?usp=sharing) (Jan. 8, 2015 edit): “DCRM2 proposes a break with DCRM1 practice. Add DCRM2 instruction.” 
 
<u>Context for transcription</u>: when I pulled the section on Transcription together, I followed the RBMS PS, which was an integrated set of instructions that included the decisions of the DCRM(B) for RDA Revision Group (2012-2014) and the DCRM-RDA Task Force (2014-2017); I read it against DCRM manuals, largely DCRM(B) and DCRM(G), to create the hierarchy and to look for omitted instructions. Iris, Michelle, and I have been working as a small group to iron out some of the last hiccups, and there are a few issues, such as this one, we wanted to bring to the group.

**Comment by rarebkcat** [comment]
The [RBMS PS Review Question 2](https://docs.google.com/document/d/1rpG4rAit5rWYUQEr_DSscXrd7xVP6jymxe0NRs5P5ic/edit) noted that this change, along with some others, was due

**Comment by lizoknj** [comment]
I found on the Google drive a document, "Walpole meeting notes Wednesday" which gives some of the background to the issue of internal punctuation within Roman numerals. This was not the official minutes, it was my extremely prolix and error-riddled notes taken during the discussion, which took place at the Fall 2016 Walpole meeting. Here it is:

https://docs.google.com/document/d/1yGqX-9C34qITkBc1XsCJu77P1sWfxtOPM8nxTi9VG2Y/edit

Try searching for the word "roman" and you should find references to the issue. In the course of trying to find a principled reason for omitting some types of punctuation and recording others, Deborah suggested that it could be useful to distinguish between "word integral" punctuation and punctuation at the end of a word. I think this may have played a role in convincing the group to change the practice to record internal punctuation in Roman numerals. But Deborah will doubtless retain much clearer memories of the issue.  And of course we may wind up coming to a different conclusion. But at least gives some context to the decision.  

Liz O'Keefe

**Comment by dcrmr** [comment]
Decision in Editorial Group meting, September 28: In keeping with the group's practice of accepting changes made by the PS editors, we will retain internal punctuation in roman numerals. Instructions in PPDM will be updated to reflect this.

**Comment by deborahjleslie** [comment]
> 
> 
> I found on the Google drive a document, "Walpole meeting notes Wednesday" which gives some of the background to the issue of internal punctuation within Roman numerals. This was not the official minutes, it was my extremely prolix and error-riddled notes taken during the discussion, which took place at the Fall 2016 Walpole meeting. Here it is:
> 
> https://docs.google.com/document/d/1yGqX-9C34qITkBc1XsCJu77P1sWfxtOPM8nxTi9VG2Y/edit
> 
> Try searching for the word "roman" and you should find references to the issue. In the course of trying to find a principled reason for omitting some types of punctuation and recording others, Deborah suggested that it could be useful to distinguish between "word integral" punctuation and punctuation at the end of a word. I think this may have played a role in convincing the group to change the practice to record internal punctuation in Roman numerals. But Deborah will doubtless retain much clearer memories of the issue.  And of course we may wind up coming to a different conclusion. But at least gives some context to the decision.
> 
> Liz O'Keefe

I am reopening this issue to state for the record my opposition to this change. Liz's memory is correct about what I said regarding punctuation integral to a word (i.e., hyphens, apostrophes, and ending punctuation expressing abbreviation) vs punctuation giving clarity to a clause. I have never, however, applied this to roman numerals. Numbers in general are problematic because of an early modern convention of using full stops preceding and following numbers when there is no intent to express abbreviation. These I've usually considered punctuation relating to the clause--although my own practice is inconsistent (see Six-Month Rule aka the Overnight Rule). 

For roman numerals, of course, we are talking about punctuation within the numeral, not surrounding it. I believe the DCRMB editors' arguments for closing up spaces and removing punctuation was to treat the roman numeral as single unit, for indexing purposes as much as anything else if memory serves. So, not treating internal punctuation in roman numerals as integral to the 'word'. Somewhat arbitrary either way. 

I object to changing this practice from DCRMB because it marks a significant departure in transcription practice without noticeable added benefit. For the record.
