### ISSUE TITLE
Clarifying which notes are required, which are optional 

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#109]
The instructions about optional vs required notes n the introduction, VIII.2 Notes, currently read:
 
"VIII.2. Notes. The instructions and guidelines in the note elements are written in imperative form. This does not imply that all notes are required; on the contrary, most notes are not (see X.X). Consult the other areas of DCRM(R) in order to ascertain what is required and what is optional in any given situation (see X.X.)."

This seems like a roundabout way of indicating which notes are optional, and which are required. The person viewing an instruction in a Note on [X] element has to take the additional step of consulting the specific element to find out if a note is optional or required. And the guidance in the specific element is not always clear:  some notes are labelled as “if considered important” (i.e. optional), some are prefaced with “always” (i.e. required), but some are not qualified in any way. If you are an experienced user of DCRM, you know that notes in Chapters 0-6 are required unless labelled otherwise, and notes in Chapter 7 are optional unless labelled otherwise, but some users won’t have this background (Deborah had to explain it to me).

One way to deal with this would be to rephrase the guidance in VIII, to read:

“All notes listed in DCRMR are required unless labelled ‘if considered important’.”

Since many people don’t read introductions, it would be just as well to add a link from every element to this passage. Or would it be better to include explicit guidance on this issue in every instruction to make a note? In other words, append “if considered important” to every optional note, and “always” to every required note. 

Or there may be a perfectly simple and obvious way to indicate this, which I haven't thought of (it won't be the first time).

**Comment by rarebkcat** [comment]
Hi, LIz--

One of the things in DCRM(B)'s appendix was a list of Required notes (under R for Required). 

Currently, we're working re-creating that (with the format modified for DCRMR's element-based construction) to go in the Notes Chapter page. (My hope is to get it in order by the end of the week.) That may address what you're asking here...?

-Amy

**Comment by lizoknj** [comment]
That would certainly be useful as an ancillary source, but having the information appear with the note would be the ideal. 

Another thought: rather than incorporating the qualifier into the instruction itself, which could get cumbersome, perhaps notes could be labelled as Optional or Required,  Or maybe we could use "blinking text"  (that was a joke).

**Comment by ladylazarus3** [comment]
LOL  oh good lord did i need a belly laugh today and Liz, you delivered! :)  i'm gonna put a nix on the blinking text (mostly because i have no idea how to do it and it might give folks seizures), but i really really like the (Optional) as it is used in [Variant title of manifestation](https://rbms-bsc.github.io/DCRMR/title/Variant-title-of-manifestation/) (e.g. [1.25.4.6](https://rbms-bsc.github.io/DCRMR/title/Variant-title-of-manifestation/#1.25.4.6)).  Can't get much clearer than that! :)  i'd make a plug for a more global adoption and implementation if other folks agree.  

kalan

**Comment by lizoknj** [comment]
I was probably thinking subconsciously of the labels in Variant title of manifestation when I made the label suggestion. Disappointed that you have rejected blinking text but I guess its time is past (well past).   

Liz

**Comment by ladylazarus3** [comment]
:)  [We were thinking about adding a rickroll-- in honor and spirit of the original test site.  Hm.  Or, maybe we did add a rickroll and no one has found it yet :) Jk. ]

**Comment by ladylazarus3** [comment]
Just looking at the DCRMR text that has been released into deployment so far, there are 169 occurrences of "if considered important" as of this afternoon.  i can pretty easily get folks a full list of citation numbers for review or add an additional label globally, if that helps?  Notepad++ has some pretty heavy duty 'regular expressions' and search capability that is useful for data mining the text.  If folks want lists of various data points, i can probably cobble together a list. :)

**Comment by lizoknj** [comment]
Note on title contains an instruction that clarifies which notes are required, which are not:  
1.29.1.3 Notes on title are required unless qualified by “if considered important.”

This is the only element to contain such an instruction. I think it is helpful, especially for new users of DCRM. But for consistency’s sake, shouldn’t every element that includes instructions on notes (not just Note on X elements) contain such an instruction? Unless there are better ways to convey this information (at one point, we spoke about labelling required notes).

**Comment by lizoknj** [comment]
List of required notes in 9.01.5:  
The list of required notes in Chapter 9 lists only twenty-nine notes. This list includes both specific notes covered in Chapter 9, and broader areas or elements or topics from other chapters, such as physical description area, publisher statements, title proper, transposition, etc., which you would have to visit and comb through to locate required notes. Are we  waiting until the text is finalized to compile this more comprehensive list, or have we dropped the idea of having such a list, at least for now?

**Comment by ladylazarus3** [comment]
>  Are we waiting until the text is finalized to compile this more comprehensive list, or have we dropped the idea of having such a list, at least for now?

Does this issue relate closely to Github issue #123?  Ideally, the relabeling of titles and/or notes as "Required" or "Optional" would make the compilation of a comprehensive list easier to maintenance.  If we go the relabeling route, ideally, a spreadsheet of citation numbers and the note's status (e.g., Optional, Required) could be created at the same time.  As far as i know, we haven't dropped the idea of having a required notes list, i think Amy and i just ran into major capacity issues towards the end of October due to the vast time-commitment of the renumbering project.

The partial list of twenty-nine notes on the [Chapter 9 page](https://rbms-bsc.github.io/DCRMR/additional-notes/#9015-required-notes) was derived from the list in the glossary of DCRMB4 and represents a mere starting point for this work.  Does this help?  What do folks think about the overall usefulness of compiling a required notes list?

kalan

**Comment by lizoknj** [comment]
I was interested in issue #123 about how to flag added titles. Deborah's suggestion that a "Required/Optional" label be inserted just below the heading for each added title sounds like an effective and easy way to deal with the issue for added titles. We could do this for a list of required notes as well. I still chafe, though, at the idea that users have to go somewhere else for this information. The instructions themselves, as they appear in the body of the text, should clearly indicate whether any given note or  added title access point is required/not required, instead of relying on a user's familiarity with the convention that notes (and added titles?) are required unless the instruction is qualified by "if considered important". But maybe I am unduly influenced by the fact that I didn't know this until Deborah clued me in back in September (oops).

**Comment by mjmascaro** [comment]
I just started reviewing additional notes, and I totally agree with Liz that we need a consistent way to denote at the element level which notes are required or optional.  It is appealing to me to come up with a uniform solution for notes and added titles, and I like want what Deborah outlined in issue #123 .

**Comment by elizhobart** [comment]
I am about to start my review of the additional notes chapter. When I met with the Keepers last Friday, we decided that as part of my review I will make a list of required notes. Right now, I think the most likely outcome will be adding (required) or (optional) labels to headings, as we have for variant title sections. I am going to leave this issue open for the time being so that we can review as a group when the work has been completed.

**Comment by elizhobart** [comment]
I've completed my review of Additional notes and an analysis of required notes, which I've added to our internal review folder here[https://docs.google.com/spreadsheets/d/1_kIym6v1HQgtNTm-xsr-g4EJ-qdi5kmZ/edit#gid=2127556503](url). The analysis is based on the "required notes" from the DCRM(B) index.

Unfortunately, I don't think this is going to be as simple as just adding (required) or (optional) to headings. For one, they don't all have a heading. In addition, this is often extremely granular. An instruction make include multiple notes and one will be required, the others not. Probably the best approach will be to make more use of "always" and "if considered important."

**Comment by lizoknj** [comment]
Thank you, Elizabeth, for doing this.A monumental piece of work. I think
you're right that labeling headings won't work for a lot of the required
note instructions, so indicators like "always" and "if considered
important" may be what we end up using. Sometimes the low-tech solution is
the best.

Liz
