### ISSUE TITLE
RDA option for recording parallel title, etc. as repeated title, etc. proper

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#11]
In Beta RDA, the preferred recording option for parallel elements (e.g., parallel title of series) is to record it as separate element proper (e.g., title of series) See [parallel title of series in BetaToolkit](https://beta.rdatoolkit.org/en-US_ala-9a2bd933-3204-3798-840a-dc55a5a237d0/div_rdv_cck_sgb).

Do we wish to state a preference?  Since it is dependent on individual systems whether it would be preferable to record as parallel elements or repeated elements, my preference is to remain silent.  

Example 

As parallel title of series.

490 1_ Europäische Hochschulschriften = $a European university papers = $a Publications universitaires européennes

As repeated title of series

490 1_ Europäische Hochschulschriften 
490 0_ European university papers
490 0_ Publications universitaires européennes

**Comment by flapka** [comment]
I maybe sorta understand the RDA principle for it recommendation, though I begin to get a headache when I ponder why the same principle doesn't apply to variant title of manifestation.

I don't feel strongly either way. If, however, DCRMR said to follow the RDA recommendation, would that mean the DCRMR could do away with parallel ... instructions altogether? (There's always appeal in paring down.)

**Comment by mjmascaro** [comment]
I checked and post 3R RDA does provide the option to record another title of manifestation  instead of using variant title of manifestation, but does not state a preference on whether to use that option or not.

**Comment by flapka** [comment]
I reached out to Kathy Glennan and Linda Barnhart for more information on the principle behind this change. Here's Kathy's response:

"[The soft deprecation of "parallel" elements] is also mentioned briefly in the following documents:
•	[RSC/Outcomes/2018](http://www.rda-rsc.org/sites/all/files/RSC-Outcomes-2018.pdf) (p. 5)
•	[RSC/Minutes/117-148](http://www.rda-rsc.org/sites/all/files/RSC-Minutes-117-148.pdf) (p. 13 - by inference)

I don't think we created any further documents explaining the principle here. Instead, it's a logical conclusion that came out of the "shredding" process. A parallel title proper is simply a title proper that happens to be in a different language and/or script. (The same goes for any of the other parallel elements.)

**Comment by lizoknj** [comment]
Thanks, Francis, for clarifying the reason for the change, and for forwarding the links It is somewhat annoying to see that parallel  and "details of" elements, data types that were subsumed under their broader data types in RDA1 and then broken out into separate elements in RDA2, are now candidates for "soft deprecation" (an Orwellian term). But c'est la vie.
I don't feel strongly about retaining "details of" as a separate element but I think it's important to be able to distinguish between parallel statements/titles and multiple statements/elements. Other things being equal, using a specific element makes it easier to make that distinction, and is preferable to a broader element when it comes to searching, display, and machine manipulation. At the moment, users can't target fields containing parallel information for searching, and must rely on a mark of punctuation to indicate that the information is parallel. Going forward, using a specific data element would facilitate more precise searching and more meaningful displays. If the broader element is used instead, I would think you would need to record to be able to record in the appropriate note field (note on title, note on series statement, note on statement of responsibility, etc.) that the statements/titles are parallel, as opposed to multiple, both for purposes of clarity, and because of the implications for authority work. This would mean splitting information between two different fields. 

I realize that RDA elements don't necessarily translate directly into MARC/BIBFRAME/whatever fields, so maybe this won't be a problem.  On the other hand, the current approach toward defining new data fields in MARC seems to rely heavily on a one-to-one relationship between an RDA element and a MARC field/subfield, so it might be wise to be cautious. I will be curious to hear how other communities react, as this isn't a done deal; the RSC will re-evaluate following the stabilization of the English text.

**Comment by lizoknj** [comment]
Correction: in my previous comment, I said that parallel titles were only identifiable by a mark of punctuation. This is of course incorrect, for the title proper, anyway. Parallel titles can be recorded not just in the 245, where the equals sign is used, but in the Varying form of Title Field (MARC 246), with indicator 1 used for parallel titles.  I think it still holds true for parallel series titles (the equals sign in the 490 string identifies the titles as parallel, if you record the titles separately, there is nothing to indicate that they are parallel).

**Comment by mjmascaro** [comment]
This discussion  brings up the broader issue of how we handle soft deprecated RDA elements in DCRMR.  While not specifically mentioned as a soft deprecated element in the RSC meeting notes, all the narrower notes on manifestation elements ([note on title](https://beta.rdatoolkit.org/en-US_ala-612acb20-84fb-3558-86b9-f75430e39843), etc.) have a statement that the note on manifestation is preferred.  Community feedback will be solicited, so these soft deprecated elements maybe officially deprecated.  Due to the broadness of this issue, it will be taken up at the editorial group at large meeting next Wednesday, June 17.

**Comment by ladylazarus3** [comment]
From a website development standpoint, if we also soft depreciate elements (e.g. https://rbms-bsc.github.io/DCRMR/docs/Series/Parallel-title-of-series/ )  would we still include these individual element pages in the overall DCRMR website with a cross-reference?  i would prefer that we just call it out in the "Changes from DCRMB" section in the preface and call it good.

Soft depreciation and no cross-reference pages would mean less to maintain, but if we truly ever get to a juncture at which we are cataloging in native RDF for production cataloging, we are going to want to add the "@language": "En" or "@language": "Fr" tags to each parallel element which would be an additional instruction than non-parallel elements.  This does seem like a significant difference in how the statements are marked up in RDF, but perhaps we could just add that to the instructions for the non-depreciated elements or handle it through an application profile instead of calling it out in our dcrmr instructions.

**Comment by mjmascaro** [comment]
At June 17, 2020 meeting, Editorial Group decided that it was important to retain parallel elements.  See [meeting notes](https://docs.google.com/document/d/11a55GuLkWWEFBg8MiQPBnuQI_pw989Tbne8nX0zNmgo/edit?usp=sharing) for more details.
