### ISSUE TITLE
Appendixes vs. appendices

### ISSUE THREAD

**Issue by hildebrand-r** [rbms-bsc/DCRMR#126]
I note usage of both "appendixes" and "appendices" throughout. Has a preference been established?

**Comment by elizhobart** [comment]
I think we've been using "appendices" more, but I don't think we have firmly established a preference. Generally, we use Merriam-Webster for spelling and usage, but Webster allows for both "appendixes" and "appendices." The Beta Toolkit doesn't seem to use either term. CMOS does use "appendixes." With that in mind, maybe we should adopt "appendixes" as our preferred term.

What does everyone else think?

**Comment by ladylazarus3** [comment]
i can change all the URLS, text, and all instances of "appendices" to "appendixes" using a global change.  From a site architecture viewpoint, i chose 'appendices.'  [(Example here)](https://raw.githubusercontent.com/rbms-bsc/DCRMR/master/_pages/Appendices/Appendix-d.md) in the current deployment there are 8 instances of "appendixes" and 29 instances of "appendices."  i can make those architectural changes for the current deployment due to CMOS style.

kalan

**Comment by elizhobart** [comment]
Thanks, kalan. To clarify, CMOS doesn't specifically say "use appendixes," but rather is the term used in the text. Since both "appendixes" and "appendices" are allowable in Merriam-Webster, we use "appendices" more, and "appendices" is built into the site architecture, my preference at this point would be to stick with "appendices" and update the 8 instances of "appendixes." If that sounds good to everyone, we can document that in the style sheet and get those changes made.

**Comment by ladylazarus3** [comment]
Sure thing, i changed them already, so i can change them back to 'appendices.' Thanks for the additional clarification on CMOS.

**Comment by elizhobart** [comment]
Thanks, kalan! I have also added this to the style sheet (under "miscellanea").
