### ISSUE TITLE
Incorporating/pointing to full membership roster in DCRMR

### ISSUE THREAD

**Issue by adams-liz** [rbms-bsc/DCRMR#143]
At the August 2022 Editorial Group meeting, Deborah L. asked about incorporating a full membership roster of past and current members into the text of DCRMR; there was agreement that this was a good idea. A full list does exist in the  [Acknowledgment](https://bsc.rbms.info/DCRMR/preface/Acknowledgments/) section of DCRMR. Text will be added to the preface that points to that Acknowledgment.

**Comment by ladylazarus3** [comment]
i was wondering if the envisioned roster serves a slightly different purpose?  For example, if we edit the Acknowledgement, which is written in Elizabeth's voice and signed by her, if it changes the acknowledgement's authorship slightly and retrospectively.  

A roster to my mind would include dates and roles for all members and years served (similar to the function of those rather dry (but incredibly useful!) [ACRL committee lists](https://www.ala.org/acrl/rbms/acr-rbmbiblio) since this group technically doesn't get one), so essentially [this membership list on the wiki](https://github.com/rbms-bsc/DCRMR/wiki/Editorial-Group-Members) complete with dates of service, but moved into the dcrmr text itself or a link added from the preface to wiki so folks can easily find the historical record of service.

Typically, i am of two minds on it.

kalan

**Comment by jess-grz** [comment]
Very good points, @ladylazarus3 and @adams-liz! Pointing to the wiki does seem to be an elegant and practical solution. I think linking from the preface will put the roster front and center.

**Comment by ladylazarus3** [comment]
i guess at the heart of it, too, is do we want the historical membership roster to appear in the PDF arranged by year?  

If so, we may want to consider moving the historical membership roster into the DCRMR text itself rather than being on the [wiki](https://github.com/rbms-bsc/DCRMR/wiki/Editorial-Group-Members).  If not, a link to the wiki should serve just as well.

**Comment by jess-grz** [comment]
One possibility is to create a new, separate page within DCRMR, perhaps after "Acknowledgments" in the preface.  It could be named something like "Editorial Group roster" or "Membership roster." 
![historical_roster](https://user-images.githubusercontent.com/44249014/190508072-f8026663-8cf4-45cb-b9e9-aae0e9a92125.jpg)

**Comment by ladylazarus3** [comment]
Should we try it on for size and see if it fits?  i could mock up the "Membership roster" page where Jessica indicated in the development branch, if folks would like that?

kalan

**Comment by ladylazarus3** [comment]
This is going to need some tweaking of sorts (and please forgive me if i misplaced or misspelled names, it got a bit late in the day), but this should give a good idea what such a [membership roster](https://dcrmr.github.io/DCRMR/preface/Membership-roster/) could **potentially** look like if a single page was inserted between acknowledgements and Introduction and organized by terms of service.

Again, this is just in the current dev environment, if folks don't like it, we can certainly take it right back out.  Just thought mocking something up really quickly might help folks by having something to squint at together.

kalan

**Comment by adams-liz** [comment]
I like the idea of having the membership roster in the text itself (it also seems in keeping with the points raised during the last meeting) and think that the mock-up looks really great, kalan! Having it broken out by year also makes sense to me. That way, we don't have to keep track of everyone's individual committee years, which isn't inherently a problem but does create a little more organizing work.

**Comment by jess-grz** [comment]
I agree! @ladylazarus3 thanks so much for creating the mock-up. I agree that this solution addresses that points raised about acknowledging membership will also being simple to update and maintain. It's very similar to what we do for the [BSC historical rosters](https://rbms.info/committees/bibliographic_standards/bscroster/).

**Comment by ladylazarus3** [comment]
<3  Oh sure!  no worries, always very happy to mock something up if folks just need to "try it on for size" to see how it fits.  If folks wouldn't mind taking a close and critical look at the accuracy of the roster lists?  i went through notes in the Gdrive folder to figure out who rotated on/off, their roles, and when, but again, i needed to quick wrap up to get to an artist reception yesterday, and there might be errors or unintentional omissions (particularly from the "before times"  the last couple of years have been a blur.   By my reckoning, it's May 838, 2020 today... but it's a Friday and that's something to be grateful for).

kalan

**Comment by jess-grz** [comment]
@ladylazarus3 I had a few edits and put the full rosters [here](https://docs.google.com/document/d/1cRzzPSkyO7APgRHRL5aTk421kFVwMD8tS59tIon6Ikg/edit#). I think I get all of the dates and people in place based on the [roster in the wiki](https://github.com/rbms-bsc/DCRMR/wiki/Editorial-Group-Members). But I'd like some fresh eyes on this, please!

**Comment by ladylazarus3** [comment]
Yeah, that was my concern, there were a few folks that the meeting minutes and the wiki didn't seem to quite match up quite right, but then again, folks don't always rotate on or off strictly by the ACRL volunteer cycle, so, grace all around.  i've updated the glossary branch with your edits as provided (thank you! <3) and refreshed the development fork.  Folks should be able to see the current lists here:  [Membership roster](https://dcrmr.github.io/DCRMR/preface/Membership-roster/)

**Comment by ladylazarus3** [comment]
okay, i need more coffee this morning, eh?  Thanks, Liz.  Fixed.  Good thing i'm not shelflisting today.

**Comment by JessieSherwood** [comment]
This seems like an elegant and sensible solution.

**Comment by io-uk** [comment]
This looks good to me. Thanks @ladylazarus3 for creating that mock-up so quickly.

**Comment by mjmascaro** [comment]
Coming out of lurking mode to comment I like the mockup and concur it is an elegant solution.  One little correction, my term as editor ended in 2019/2020 and I was a regular member in 2020/2021.  Other than that the rosters match my memory of membership in the before times.  Thanks @ladylazarus3

**Comment by ladylazarus3** [comment]
<3 <3 <3  Thank you, @mjmascaro.  <3  Absolutely.  Those changes should be in the [glossary branch](https://dcrmr.github.io/DCRMR/preface/Membership-roster/) now, and thank you, as ever for your sharp eyes and for double checking the list for us.  <3  We are delighted to have lured you out and miss you.  <3

kalan

**Comment by deborahjleslie** [comment]
All looks great, and the chronological order will be the most useful. At some point, the editorial group will need to decide what to do about the preface; perhaps that can be addressed with the next release.

**Comment by deborahjleslie** [comment]
I made this suggestion earlier in a zoom meeting, so forgive me if it was considered and discarded. 

What do others think about using the designation "Chief Editor" instead of just "Editor"? I consider that everyone in the group is an editor, with chief editors retaining final responsibility. The phrase "chief editor" was used at first informally in the DCRM suite, until Erin C. Blake was presented formally as "Chief Editor, DCRM(G)." 

_If we want to appear ahead of the curve, we could lower-case the titles: chief editor, keeper of the text._  (-;

**Comment by jess-grz** [comment]
I think that would work quite well @deborahjleslie, and it's good to hear about precedent for this wording. My one concern is that there will be quite a bit of extra text. To prevent the extra text from drowning out the member names, how does everyone feel about italicizing the roles in the [membership roster](https://dcrmr.github.io/DCRMR/preface/Membership-roster/)? So it would look something like this:

**2022/2023**

Liz Adams, _chief editor_
Erin Blake, _editor_
kalan Knudson Davis, _keeper of the text_
Laura Doublet, _editor_
...

This italicization (and also the lowercasing that Deborah suggests) of roles is in line with what we do for the [BSC historical rosters](https://rbms.info/committees/bibliographic_standards/bscroster/), FWIW.

The current roster in the preface could be updated to reflect the editor role:

**RBMS RDA Editorial Group (2022/2023)**

**Chief Editors**

Liz Adams, David M. Rubenstein Rare Book & Manuscript Library, Duke University
Jessica Grzegorski, Newberry Library

**Editors**

Erin Blake, Folger Shakespeare Library
Laura Doublet, University of Victoria, Victoria, B.C.
Tammy Druash, University of North Florida
...

At this stage, I think we would be able to roll any edits to the preface in with the glossary and summer edits.

What do others think?

**Comment by adams-liz** [comment]
I like italicizing roles in the membership roster, Jessica. I think as long as the only updates we're making to the preface right now involve Editorial Group member names, rolling the edits in with the glossary and summer edits makes sense to me (but please, kalan and Amy, let me know if there's something big I'm missing about that). There will be additional changes to the preface with the integration of DCRMG, and so I worry a little about syncing of text in multiple places, something that came up recently in a different conversation with the keepers.

**Comment by ladylazarus3** [comment]
Hi folks,  

i've implemented the changes by @jess-grz into the [membership roster page on the development branch](https://dcrmr.github.io/DCRMR/preface/Membership-roster/) including all roles in italicized text.  If *editor* gets too busy and repetitious as to make one's eyes glaze over, we could leave it off entirely and change the top sentence to say, "Editors of the RBMS RDA Editorial Group, listed by terms of service:" (rather than beginning that sentence with "Members") implying that everyone without a specific role listed is an editor, and those with roles have additional organizational responsibilities.

re: capitalization, i agree with @deborahjleslie. i think it is a subtle nod to power intelligence without being preachy.  i like it.

re: everyone as editors.  Particularly, i like everyone being considered *editors* rather than members because i think that term is certainly accurate, reflects the incredibly dedicated commitment of absolutely everyone involved, certainly, and for those of us on academic tenure or tenure-like employment tracks, it is a word that carries a lot of weight with promotional committees.  It is too late for me in this respect (my dossier is currently under review), but it will help others make strong cases into the future.

re: preface updates @adams-liz, i agree that it would be good to roll the preface updates into the summer edits updates.  i feel like this specific issue regarding the membership roster page is really being close to being resolved (i hope others agree!), and any additional feedback on the preface would be good to address separately via the current release cycle.

kalan

**Comment by jess-grz** [comment]
@ladylazarus3 thanks so much for modifying the mock-up with the italicized text! I don't think this looks too busy, and it clearly gives credit to all group members. I agree it's important to make the editor role explicit, both to give due credit to the hard work of our group members and for those creating dossiers for tenure/promotion.

@ladylazarus3 @adams-liz yes, we can certainly roll the preface updates into the summer edits. We actually already have edits to this portion of the preface ready to go in the summer edits doc, since we were already planning to update the membership roster there for our current group.

**Comment by ladylazarus3** [comment]
Sounds perfect!  <3  Thanks, everyone for the fantastic input and working through this together.  All hearts and infinite appreciation to and admiration for you all,

kalan
