### ISSUE TITLE
Sources of information for physical description

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#15]
All the Google dox elements for physical description currently include an instruction to use the “resource itself” (“manifestation” will replace “resource”) as the source of information. This instruction appears in both the main element (e.g. Layout) and in the note on/details of element (e.g. Details of layout). This instruction doesn’t seem necessary for the note/details elements, since notes related to other types of information don’t include such an instruction. Can it be deleted? 

I also wonder whether a more nuanced instruction might be better for the main element. For purposes of comparison, here is the way the PSs treated sources of information for physical description (the PSs used the same instruction for the main element and for the note/details element):

“Use evidence presented by the resource itself (or on any accompanying material or container) as the basis for recording the [extent/dimensions/etc.] of the resource. Take additional evidence from any source.”

Not sure if “accompanying material or container” should be retained, but the rest of the PS instruction seems like a more accurate description of how information on physical description is generated and presented. Even in the main elements, the information is usually not transcribed, but presented in the form of controlled terms or standardized measurement; for rare books, there is also more reliance on external sources for information on physical characteristics.  (e.g. the font sizes from Proctor). Ultimately, the source for all the information, even if at second-hand, is the manifestation itself—but this seems like a truism.

What do others think about this?

**Comment by deborahjleslie** [comment]
Liz, can you provide a link to a document that exemplifies the discussion?

**Comment by flapka** [comment]
@deborahjleslie A couple of examples: 
https://docs.google.com/document/d/1uOo8jnWIIl5HalSFl7MKtlAwIx32azB2Mmd0fKz2NoM/edit
https://docs.google.com/document/d/1TyCvZO6dPvgk-3MnIpmWg97-lDWxDyhvV-xFhycTwfA/edit

**Comment by flapka** [comment]
I think I learn towards agreement with Liz's suggestion, to have a source of information along the lines of:

“Use evidence presented by the resource itself (or on any accompanying material or container) as the basis for recording the [extent/dimensions/etc.] of the resource. Take additional evidence from any source.”

If we are worried about the trouble of different "source ..." formulations we could limit ourselves to boilerplate along the lines of "from a certain page ..." or "from the resource" or "from any source." But I think the sort of nuance Liz describes is preferable.

**Comment by mjmascaro** [comment]
I do agree that "Use evidence presented by the resource itself (or on any accompanying material or container) as the basis for recording the [extent/dimensions/etc.] of the resource. Take additional evidence from any source" is from more descriptive of how physical description information is generated than the wording used in the DCRM modules.  One my own reservation, is that specific wording is from RDA proper, versus something written by the PS writers.  (See [draft PS for Book Format](https://docs.google.com/document/d/1a46PwA70kvIrN2rVWoz6unO20bDlfuXRdRLFR4ywvCk/edit)).

**Comment by lizoknj** [comment]
Michelle is quite right, the specific wording is from RDA proper, not the PS editors. Just to confirm : As a general rule, when there is text on the left-hand (RDA) column but not on the right-hand (RBMS PS) column, the general import of the RDA instruction is/was acceptable, but may need to be reworded to be compatible with DCRMR?

**Comment by mjmascaro** [comment]
To answer Liz's question, yes, in these case the general import of the RDA instruction is/was acceptable.  We just do not own copyright to RDA column so we cannot copy the wording into DCRMR.

**Comment by mjmascaro** [comment]
From June 8, 2020 text finalizing group meeting minutes
The more nuanced language for sources of information, while perhaps desirable, is of RDA authorship, so we probably cannot parrot it. 

Liz will propose new language for the elements in her sections, after which we will continue the discussion.

Do we want to specify manifestation in sources of information (instead of resource) -- because in practice we do generally catalog from a copy in hand?  Tentatively, we agree (?) that it’s appropriate to maintain a reference to the manifestation

**Comment by deborahjleslie** [comment]
Ok, I've now taken the time to study the issue, and apologize for not being prepared for today's meeting, and indeed for not realizing quite what the issue was. 
 
It seems like we're tying ourselves into knots trying to explain to catalogers how to get additional information for imperfect copies in hand, when in my view, the real problem is a confusion with (or possibly, within) the Toolkit itself. 

"Recording a source of metadata" and "Recording source" are not synonymous. 
- "Recording a source of metadata" https://beta.rdatoolkit.org/en-US_ala-cfa18e03-17f2-378a-874c-86515bf7e0ac/section_gr4_l4l_5cb makes it clear that it encompasses metadata of all sorts, not just transcribed data. 
- "Recording source" https://beta.rdatoolkit.org/en-US_ala-403ad4e9-451a-35bb-877a-bd9155358a30 makes no sense to me. Seriously, what does this even *mean*?: "A source of information for a metadata work that is an unstructured description transcribed from a manifestation that is being described."

First step is to revisit the DCRMR draft of the general rule on Data provenance, broaden it to encompass the entire scope of recording a source of metadata. Then we can go back to a concise instruction in the physical description elements: "Take information for this element from the manifestation itself. Take additional information from any source."

**Comment by elizhobart** [comment]
My apologies for any confusion generated by the draft of data provenance guidelines; this was just a first draft and not intended for use yet! I agree that broadening will be necessary here. I am hoping to revise it this week.

**Comment by deborahjleslie** [comment]
Hello Elizabeth, and no worries! 

I started to write some infelicitous mutterings about RDA Beta, but will leave the gist for later. For the meantime, instead of scoffing about *Stable* English text, I cast mutterings on Stable *English* text. Am certainly not the first, nor the last, to do so.

**Comment by lizoknj** [comment]
The first link is to a section within Data provenance, which is guidance on
all sorts of metadata, including metadata about the metadata, e.g. the
language and script of the description, the content standard used for the
metadata, the timespan during which the description is valid.  The second
link is to a data element for recording the source within a manifestation
for  transcribed information, e.g. title page, caption, cover.

Deborah's comment clarifies what has been perplexing me about this issue of
source for physical description. As I interpret it, the RDA Data provenance
guidance does not explicitly address the situation iwhere description is
not based on "content", but on observation of physical characteristics of
the resource. Here is what it says about a manifestation being the source
of the description:

"A source of metadata may be a manifestation that is being described or
another manifestation.

A manifestation that is being described may carry textual content that can
be transcribed or otherwise used as a source of information for a metadata
work about the manifestation.

A manifestation may carry content that can be used as a source of
information for a metadata work about any RDA entity."

It sounds to me as if "textual content", transcribed or non-transcribed, is
the only source of information for description. Maybe I am misinterpreting,
and content encompasses extent, dimensions, production method, etc. But it
could be spelled out a little more clearly in RDA. Otherwise, it would seem
as if RDA does not cover even the physical description of perfect copies.

Liz O'Keefe



.

**Comment by elizhobart** [comment]
I have updated the data provenance general rule from "Where possible, transcribe metadata from the item in hand" to "Base the description on the item in hand." This should broaden the scope and also uses wording from the PS draft and DCRM(B) 0B2.1. I think this should address the concerns, but let me know if any additional changes are needed.

**Comment by deborahjleslie** [comment]
Thanks, Elizabeth; this sounds right to me.

______________________
Deborah J Leslie (she/her) | Senior Cataloger | Folger Shakespeare Library | 201 East Capitol Street, S.E. Washington, DC 20003 | djleslie@folger.edu<mailto:djleslie@folger.edu> | www.folger.edu

**Comment by lizoknj** [comment]
Yes, that clarifies that transcription is not the only source for recording
information.  Thanks, Elizabeth.

Liz

**Comment by lizoknj** [comment]
For your consideration tomorrow, here is a suggested Sources of information instruction for the physical description elements (excluding the details of/note on elements, which don't need sources of information instructions):

"The source of information for this element is the manifestation itself. Take additional information from any source."

Liz

**Comment by ladylazarus3** [comment]
Quick question on source of information-- do we see Sources of information as a section repeated on every entity page (for example [Note-on-RDA-entity](https://rbms-bsc.github.io/DCRMR/books/other-notes/Note-on-RDA-entity/#7233-sources-of-information) and [Publication statement](https://rbms-bsc.github.io/DCRMR/books/ppdm/Publication-statement/#4203-sources-of-information), or do we see source of information generally included at the chapter level (for example, [the chapter level page for ppdm](https://rbms-bsc.github.io/DCRMR/ppdm/) or [chapter level page for Other notes](https://rbms-bsc.github.io/DCRMR/other-notes/)?  Or both?  It wasn't in the [original re-write template](https://docs.google.com/document/d/1tAqoqjVBtx4GeBbXn8Hvn-FpB8d5mt3MRUgMl5QYye4/edit) so i just wanted to double check with what everyone was thinking.

i'm just asking because i might want to add a section for sources of information to the GitHub [entity template](https://github.com/rbms-bsc/DCRMR/wiki/Template:-Entity-Template-for-DCRMR) and [instructions](https://github.com/rbms-bsc/DCRMR/wiki/How-to-populate-a-new-Entity-Markdown-file).  Very do-able,

The PRO of having source of information included on each entity page instead of each chapter page is that folks are sure to see it as they read through the sections/instructions for each entity.  

The PRO of having source of information included on the chapter page instead of each entity page is that it wouldn't have to be repeated for each and every element.  

i'm sorry if this is a repeat of a discussion we've already had-- i just more or less wanted to check my own assumptions.  Thanks for your thoughts and patience with me.

**Comment by lizoknj** [comment]
Very good question. As you say, pro's and con's either way. If we think of the instructions as RDA elements, the instructions ought to appear within every element, because there is no overarching organization. If we think of the instructions within the context of DCRM, then it seems better to put them at the highest point in the chapter where they apply , with links from instructions below. This would eliminate repetition, and make updates to the text easier. LizSent from my Samsung Galaxy smartphone.
-------- Original message --------From: kkdavis <notifications@github.com> Date: 7/17/20  12:26 PM  (GMT-05:00) To: rbms-bsc/DCRMR <DCRMR@noreply.github.com> Cc: lizoknj <lokeefe411@gmail.com>, Author <author@noreply.github.com> Subject: Re: [rbms-bsc/DCRMR] Sources of information for physical description
  (#15) 
Quick question on source of information-- do we see Sources of information as a section repeated on every entity page (for example Note-on-RDA-entity and Publication statement, or do we see source of information generally included at the chapter level (for example, the chapter level page for ppdm or chapter level page for Other notes?  Or both?  It wasn't in the original re-write template so i just wanted to double check with what everyone was thinking.
i'm just asking because i might want to add a section for sources of information to the GitHub entity template and instructions.  Very do-able,
The PRO of having source of information included on each entity page instead of each chapter page is that folks are sure to see it as they read through the sections/instructions for each entity.
The PRO of having source of information included on the chapter page instead of each entity page is that it wouldn't have to be repeated for each and every element.
i'm sorry if this is a repeat of a discussion we've already had-- i just more or less wanted to check my own assumptions.  Thanks for your thoughts and patience with me.

**Comment by elizhobart** [comment]
My preference is to have these at the chapter level. If we include this with every element, it will increase clutter on the page and will be repetitive, since in general every element in a chapter will have the same sources of information. In addition, if we change a preferred source of information in the future (perhaps as we add additional modules), we'd have to maintain every repetition of this text. Since chapter-level organization is available in the left-hand sidebar, it should be clear enough to leave it at the chapter level.

**Comment by flapka** [comment]
I agree with Elizabeth's arguments for putting SOI at the chapter level. I'd be okay with either:
* No mention of SOI at all, at the element level.
* For each element, a (graphically discreet) "Sources of Information" link to the pertinent information at the chapter-level

**Comment by lizoknj** [comment]
Usually there is a one to one relationship between the RDA "manifestation [series/edition/title and statement of responsibility] statement" and the DCRM area, but sometimes not. I am thinking of Chapter 4, PPDM area, and Chapter 5, Physical description area, where there is no RDA element corresponding to the scope of these DCRM chapters. For these two chapters, I guess we just repeat the SOI instruction at the highest possible level, so the SOI would appear at the publication/manufacture/distribution statement level for Chapter 4, and at the individual element level for Chapter 5 (darn, I was hoping I could save myself some typing).

**Comment by ladylazarus3** [comment]
Thanks @lizoknj .  i see now that we are just going to have to roll with it instead of having a hard and fast rule.  i think we are getting really close folks.  To that end, i've mocked up an example of what the SOI would look like when it is recorded at the highest level (e.g. chapter 4).

Here is the (hopefully) visually unobtrusive source of information on the [name of publisher page](https://rbms-bsc.github.io/DCRMR/books/ppdm/Name-of-publisher/#4.203.1.2) and here is a mock up of the SOI on the [chapter page](https://rbms-bsc.github.io/DCRMR/ppdm/#42-sources-of-information)

What do folks think about this?

**Comment by lizoknj** [comment]
Yes, I think that works very well. It would be great to do the same for
Physical description.

Liz

**Comment by ladylazarus3** [comment]
@lizoknj of course!  the current version of the [Physical description chapter page](https://rbms-bsc.github.io/DCRMR/physical-description/) is really bare bones right now, but we could certainly do something similar for each chapter as appropriate.   i've been struggling with what to put on these pages, but i think it makes sense to make these pages work much, much harder for us than simply list the entities included in that particular chapter.
