### ISSUE TITLE
Reference to Recording Relationship to Related Works

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#20]
In [7B12 Note on Series Statement](https://docs.google.com/document/d/18_NANtMycMR8NcQj0s0oMcqcd-lNwEsz8UueW8vgLZo/edit#bookmark=id.re1msn7e7vxe) there is following instruction:

Give information about a series in which the publication has been issued previously if considered important. For information about a series in which the publication has been issued previously, **see Recording Relationship to Related Works.**

The last sentence was taken from the [draft PS](https://docs.google.com/document/d/1NW990v3mx1KPcDEvgsLm659jel2o5W_4LjZlnbcOaRs/edit#bookmark=id.82lpdthhzwb).  Relationships to Related Works is no longer a section in the post-3R Toolkit.  The pre-3R Toolkit sections on relationships included instructions for unstructured descriptions, so some notes instructions from DCRM(B) were mapped to these relationship sections.   

Given the changes to relationships in the post-3R Toolkit, I think it makes sense that this DCRM(B) instruction would mapped to to "note on series statement" in DCRMR.  Would mapping any similar references to recording relationships from the PS to notes be a good principle moving forward?

**Comment by deborahjleslie** [comment]
That makes the most logical sense for a minimum viable product, and we'd already decided to go with the more specific element rather than "note on manifestation" for such things. 

I'd like to point out, though, that we're presumably talking about a manifestation that does not carry the previous series statement, right? Else we'd transcribe it and not have to relegate it to a note. 

So it's not a note on the series _statement_, which is a manifestation element. The content appearing as part of another series makes it a different manifestation. We're really talking about a note on series as an expression-level element. Which doesn't exist, and we'd have to bump it up to 'Note on expression.' 

This issue comes up of course with "note on statement of responsibility," where we give attributions for anonymous or pseudonymous manifestations. 

At the moment, I'm less comfortable with shoe-horning our text into RDA elements where they don't belong. Is the problem that we want to put instructions for all notes relating to an element with the element? I'm going to open this as a new issue since it's a broader conceptual problem.

**Comment by lizoknj** [comment]
In many cases, the name of the former series does appear on the manifestation (I'm thinking of facsimiles and reproductions). But since it's not the series statement for the manifestation you are cataloging, you can't transcribe it as a series statement. I wish there was still the RDA option to treat it as a relationship to another manifestation. Absent that, it seems marginally preferable to put it on a note on series statement.
