### ISSUE TITLE
 (RDA) Vocabularies. [from Gdoc]

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#21]
Original Post from Francis on Feb. 3, 2020

These questions are posed in the context of terms for illustrations and for format, but there will be other applicable contexts too. 

1. My memory says we decided to always use the RDA prescribed vocabulary, where applicable -- with the added condition to choose another term if none in the list suits. Is that correct?
2. Do we want to adopt a consistent formatting/syntax? Two primary options are paragraph style, as embodied in DCRM (see illustrations), or list style, as embodied in RDA (see format). I think either would do. 

[MM: 
Your memory is the same as mine.  Looking at comparable instructions in the Post 3R Toolkit, it looks like their preference is to choose a “term from another suitable vocabulary encoding scheme.” versus supplying anything which makes sense for the linked data environment.  (Let’s avoid blank nodes.)  Do we wish to follow suit in that wording?
I think we settled on RDA style, right?]

**Comment by mjmascaro** [comment]
Liz posed similar question on these sections, at [June 8th DCRMR Text Finalizing Meeting](https://docs.google.com/document/d/1DjGabnwyuLJjkYnHcjd1b17bXAt6vYvIPvuE3unwdbs/edit#bookmark=id.xtudkpm4u3up) which had the following conclusion:


For the elements associated with controlled vocabularies:

- For now, it is useful to provide links to good sources of terminology (e.g. RBMS CV, AAT, etc.)
- When we progress to work on non-book formats, esp. Graphics, we may want our guidance to name some of the most frequently used pertinent terms

**Comment by lizoknj** [comment]
Several of the physical description elements include recommendations to use terms from the RDA Vocabularies. I would like to include links to these vocabularies, but I am wondering  whether the links should be to the RDA Toolkit (which is subscription only) or to the RDA Registry (which is publicly accessible)?  The URL will be different, depending on which source is used, and the name of the vocabulary will be different, too ("Vocabulary Encoding Schemes: RDA Content Type" in the Toolkit versus "RDA value vocabularies, RDA Content Type" in the Registry). 

Also, what is the preferred style for including a link to an external URL? Should it be entered as a actionable link (in red) to the name of the resource, or as the name of the resource, followed by the URL, in parentheses and in red?

**Comment by flapka** [comment]
That's a good question. In addition to the Toolkit and Registry options, I believe all (?) RDA VESs are represented in [id.loc.gov](http://id.loc.gov/). 

Compare the three option for production method: [Toolkit](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-9bdf25b8-f2f7-31d1-a3a0-7f416e4bc667&highlight=production&highlight=method), [Registry](https://www.rdaregistry.info/termList/RDAproductionMethod/), [id.loc.gov](http://id.loc.gov/vocabulary/mproduction.html). 

In haste, my preference is probably

1a. Registry
1b. id.loc.gov
9. Toolkit

I like that the Registry's incorporates term list and definitions in one view; while id.loc.gov manages to list terms in full alphabetical order (Registry has newer (?) terms at end, outside of alphabetical order).

**Comment by lizoknj** [comment]
I agree that Toolkit is the least preferable (apart from everything else, it keeps accusing me of Maximum Concurrency and locking me out).

I didn't make a full comparison between the RDA Vocab list and id.loc.gov, but I discovered that some RDA vocabularies, such as  Material and Bibliographic Format, are missing, and that the LC list includes non-RDA vocabularies in the list (e.g. Govt Publication Type, Script). That wouldn't be so bad, but bafflingly, LC does not identify the source of the vocabulary, so you don't know which vocabs are RDA and which are not. Maybe because they have edited them pretty freely? Again, I haven't checked everything, but the LC Illustrative Content vocab still includes "music". So I would vote for Registry.

**Comment by ladylazarus3** [comment]
a few more thoughts, in case we want to consider them.  Instead of having some of these terms link externally, we have them link to an Appendix with out-of-scope elements (and their various mappings to RDA and other datasets) or include them and have them link to their respective term in the DCRMR Glossary.  That way the links within DCRMR retain our own branding and stability.  From a web/dev point of view, it would be helpful for all the external links to be in "one spot" for maintenance purposes.

**Comment by lizoknj** [comment]
Just to clarify, I was asking about links from names of external vocabularies, rather than links from terms within these vocabularies. The former could usefully be grouped in an appendix on external resources. That said, Kalan's suggestion about linking to a single place for links to external sources would be the ideal approach, in the interests of maintenance and internal consistency.

**Comment by elizhobart** [comment]
Discussed in July 29 meeting. The group expressed a preference to link to the vocabulary, but state directly if there are terms we will not be using or, if only using certain terms in a list, to name them explicitly. This will save space and allow for more flexibility as vocabularies are updated. 

We will need additional discussion about source of RDA terms, either from the RDA registry, id.loc.gov, or the Toolkit. There is a general feeling that the RDA Toolkit is least preferable, as it is a subscription resource.

**Comment by elizhobart** [comment]
Outcomes from August 12 meeting: the group generally prefers the registry. However, one group member reported being unable to load the registry. For now, we will proceed with using the registry but will be mindful of potential loading problems. In addition, we will continue to link to instructions in the Toolkit.
