### ISSUE TITLE
Dissertation statement (M) and Dissertation or thesis information (W)

### ISSUE THREAD

**Issue by flapka** [rbms-bsc/DCRMR#23]
(Apologies if this issue has already been discussed.)

With 3R, RDA gives us a new element for [Manifestation: dissertation statement](https://docs.google.com/document/d/1_dU8Vs-2SqTQHlsbeyMOjQOYABW9hV6tQZTjNAhmyVU/edit#heading=h.rkgo3gie23qj), alongside the element for [Work: dissertation or thesis information](https://docs.google.com/document/d/1-yzjbsXboMP5-ghi29sN9u0IPQRnqU_Hvz0mgoZXuLE/edit#heading=h.ujwm4pj2car4). The first is a manifestation statement. The second is recorded, with subelements for degree/institution/year -- more-or-less aligned with DCRM(B)'s guidance in [7B13 Dissertations](http://desktop.loc.gov/search?view=document&id=Infobasedcrmb0Dash0Dash0Dash920#). 

Questions:

1. Do we want to maintain DCRMR guidance for both elements? (Probably?)
2. Do we want DCRMR guidance to encourage use of one over the other?
3. We also need to find a logical home for data describing bibliographic history, as mentioned in this instruction: "If the publication lacks a formal thesis statement, a bibliographic history note may be made." I'm inclined to put it with History of Work. The meaning of that element [is clearer in the old Toolkit](http://access.rdatoolkit.org/rdachp6_rda6-3332.html), thanks to the examples.

**Comment by ladylazarus3** [comment]
i would think we would *eventually* want guidance for both elements.

We could potentially get around encouraging use of one over the other (for now) by saying that the Work elements are out of scope because 1) we would encourage folks to follow eventual LC/PCC practice 2) state that there isn't really a rare materials reason to deviate from local institutional policy or 3) say that these additional work elements are not part of a Minimal Viable Product.

i agree that [History of the Work](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-6991c355-409b-37af-8ded-8902061f40e8) seems to fit, although i suppose [Note on manifestation](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-2f069b6a-bc80-3498-ba25-28ec7d8672c2) might be a new catch all (similarly to how MARC 500 is now), or is that completely off base?

**Comment by elizhobart** [comment]
These elements were an especial pain when I was drafting them. At the time, I didn't really understand manifestation statements. With my current understanding, I would advise omitting guidance for manifestation dissertation statement and instead provide guidance for the work-level elements. At this juncture, we're not providing guidance for other manifestation statements (I believe?) and don't see a reason to make an exception here. (To clarify, these are elements such as "manifestation title and statement of responsibility" versus "title proper," a manifestation-level element.)

To respond to your questions:

1. In the long run, we probably will want to maintain instructions for both, but for now, let's stick to the work-level dissertation or thesis information. We can come back to manifestation dissertation statement at a later date, especially if taking a closer look at manifestation statements.
2. This is probably answered by #1. Ultimately, manifestation statements serve a different role, so this information (as I understand) should be recorded as work: dissertation or thesis information.
3. History of work makes sense to me.

Francis, will this be enough to move forward? Or would you like to schedule this for discussion at an editorial group meeting?

**Comment by flapka** [comment]
kalan rightly notes that DCRM guidance usually takes interest in Manifestation attributes over related attributes of a Work. But I guess this is an exception. DCRM precedent suggests that transcribed dissertation info doesn't serve significant user need (to identify) -- and that the recorded (work) info is more important.

As Elizabeth suggests, I'm okay with including only the Work element for now -- to reconsider the M element later. In the aim of saving time, I'm okay if we don't discuss the question among the group.

**Comment by elizhobart** [comment]
I agree that generally we should map to Manifestation elements rather than Work, but I think this one is an exception since the Toolkit only makes it available at the manifestation level as a manifestation statement. The difference between "manifestation dissertation statement" and "Manifestation: dissertation statement" is subtle, to say the least, but since "Manifestation: dissertation statement" doesn't exist, I think the Work-level element is our best option.

**Comment by flapka** [comment]
When headaches intersect: The last two instructions in DCRM(B)'s guidance for dissertations are as follows:

> If the publication is a revision or abridgment of a thesis, state this.
>> Abstract of thesis--Yale College, 1795
> 
> If the publication lacks a formal thesis statement, a bibliographic history note may be made.
>> Originally presented as the author's thesis (Universität Heidelberg) under title: ...

As I look at this now, I think the guidance would map to RDA elements for abstract of .., revision of ...,  and/or reprint of manifestation of .... (adding *abstract of* to the list of relationship elements we might need to add, as noted in GitHub issue #23).
