### ISSUE TITLE
Additional acronyms?

### ISSUE THREAD

**Issue by brownbbz** [rbms-bsc/DCRMR#25]
What additional acronyms should be added?

Suggestions thus far include:
BIBFRAME, CONSER, LC/PCC PS, MARC, RBMS PS, BSR, 3R Project, FRBR. In addition, maybe add the other DCRM manuals?

**Comment by mjmascaro** [comment]
BSC (Bibliographic Standards Committee)?  It is used in the current draft of the Preface-Background.

**Comment by brownbbz** [comment]
I added Library Reference Model (LRM).

**Comment by ladylazarus3** [comment]
add RSC?  Rda Steering Committee?
Chartered Institute of Library and Information Professionals (CILIP)?
(not sure if these are in the text anywhere, however).

**Comment by ladylazarus3** [comment]
Hi folks,

i've made a [draft pull request for the Acronyms.md file](https://github.com/rbms-bsc/DCRMR/pull/82/files) adding most of the terms noted above in this GitHub issue.

One question i have (and it might be appropriate for our CC:DA rep to find the answer for us) is whether CC:DA is undergoing a name change as well as its division ALCTS.  Right now, the CC:DA entry reads, "Committee on Cataloging: Description and Access, Association for Library Collections and Technical Services, American Library Association" which since ALCTS was dissolved and CORE was implemented on Sept 1st, this entry may need further adjustment.  

let me know your thoughts.

kalan
