### ISSUE TITLE
Related manifestations -- Do we align guidance with more granular elements?

### ISSUE THREAD

**Issue by flapka** [rbms-bsc/DCRMR#28]
Our drafts include a document for [Related manifestation of RDA entity ](https://docs.google.com/document/d/1ci6PF31FKjpRFRlayhOQCrnTyBp9kdaIyGtwNGIjUBs/edit#heading=h.rkgo3gie23qj). This guidance is derived from DCRMB 7B7.2.

In our draft PSs, 7B7.2 was echoed in [Related Manifestations](https://docs.google.com/document/d/1fQpb5QvP7DFiuwOOp2Qb2gbFJsStC_X1Z8dDye-z6Rk/edit#bookmark=id.ln1luaho9us0). Now that separate relationship designators have evolved into separate data elements (joy!), does DCRMR need to parse out guidance at a more granular level, e.g. for the Beta Toolkit's [reprint of manifestation of ](https://beta.rdatoolkit.org/en-US_ala-d83588be-4edb-309c-8ace-ac9bc6311d2b) or [accompanied by manifestation](https://beta.rdatoolkit.org/en-US_ala-c700044a-97ee-3f4b-8ac3-2139c2e827ca). We've already parsed out [issued with](https://docs.google.com/document/d/1YVu7GaVV_l3WzeYNPDnpPYd2nLcpvGx_k8FGf9q9Qno/edit#heading=h.rkgo3gie23qj), which is also farther down on the [related manifestation of manifestation](https://beta.rdatoolkit.org/en-US_ala-b716f212-6108-3c94-8067-2b46828562c2) hierarchy.

**Comment by ladylazarus3** [comment]
Here is a thought on how we could do this in the DCRMR website (this may be a bad thought).  Since much of the guidance for these various elements is each derived from 7B7.2, what might happen is this...  we collocate the more granular elements as different sections of [Related Manifestations of RDA entity](https://rbms-bsc.github.io/DCRMR/books/other-notes/Related-manifestation-of-RDA-entity/) page. 

i've created a [mock up here](https://rbms-bsc.github.io/DCRMR/books/other-notes/Related-manifestation-of-RDA-entity/#7.23.5.1)  of what this might  **potentially* look like... just as a thought experiment only... i'm not advocating one way or the other.  This is just one solution and i think catalogers would have a sense to look for some of these relationship type elements in the same spot anyway... and RDA seems to put them in the same spot too.

The PRO of this approach would be that 1) the granular elements are collocated together on a page where folks expect to find them together 2) the TOC navigation side bar doesn't have an explosion of yet more RDA elements.

The CON would be that we are sort of breaking our rule and self-imposed guidance that every RDA entity has its own web page and the text of the various sections derived from 7B7.2, 5E2, etc., might be repeat a bit.

**Comment by flapka** [comment]
Thanks for mocking this up, kalan. I find that approach interesting and (probably) preferable. Curious to hear what others think.

**Comment by elizhobart** [comment]
I like the mock-up, kalan. The downside, as you note, would be that it's breaking our own rule regarding elements having their own pages, but I also think you're right that catalogers would likely look for them together. This approach makes sense to me and seems like a sensible reason to depart from our standard practice. What do others think?

**Comment by flapka** [comment]
As I dig a little deeper with this section, I find bigger headaches (or am I merely looking for trouble)? Looking just at warrant established by usage in DCRM(B), it appears that DCRMR would require the following relationship elements:

* Translation of (E): see 7B2.1
* Adaptation of (W or E): see 7B2.1
* Revision of (E): see 7B7.2
* Succeeded by (E): see 7B7.2
* Reprint of manifestation of (M): see 7B7.2
* Accompanied by (M): see 7B11
* Issued with (M): see 7B18.1
* Bound with (I): see 7B19.3.4

And that doesn't include the inverses! And subsequent formats will add quite a few more elements (esp. serials). 

As you can see, these are variously subelements of  related E ..., related M, or related I. 

Questions:
* A number of these elements are not in our Order of text spreadsheet. Do we need them?
* RDA organizes relationship in a deep hierarchy for which the top element is "related RDA entity of RDA entity." In terms of organization/order, would it make sense for DCRMR to follow suit?
* On granularity: Is there any utility in even articulating the broader-concept elements (e.g. Related manifestation of RDA entity), or should DCRMR zoom straight to the narrow elements that we actually plan to use?

**Comment by elizhobart** [comment]
Short answer: I don't think you're not looking for trouble. These kinds of issues, often with exactly these elements, seem to come up for anyone developing RDA-related standards. 

I think that the broad issues should be discussed with the group, so I am going to schedule this for our next meeting. My thinking:

- Order of text: If we're going to add instructions for them, they should probably be included in the spreadsheet
- On organization and granularity: I think it's okay if DCRMR does not mirror RDA. We're already deviating in other places, so I think it's okay to do so here, as well, for the sake of utility. In addition, many of these relationships will become more apparent as we draft PSs. So, I think just zoom to the narrow elements we plan to use and not worry too much about the hierarchy.

I am eager to hear what everyone else thinks.

**Comment by ladylazarus3** [comment]
Q: A number of these elements are not in our Order of text spreadsheet. Do we need them?
+ Yes, they should be added.  if we *do decide* that "relationship elements" can be collocated on the same page for ease of use and to manage expectations from catalogers, we can always just add the section numbering and along with entity and chapter numbering and link to that particular section.  i really like how Francis called them "relationship elements" as well.  that seems to be a good way to refer to them if we don't like the cumbersome RDA label.  Call a duck a duck.

Q. RDA organizes relationship in a deep hierarchy for which the top element is "related RDA entity of RDA entity." In terms of organization/order, would it make sense for DCRMR to follow suit?
+  i agree with Elizabeth that i think it's okay if DCRMR does not mirror RDA.  i think we need to channel our inner Seymour Lubetzky and ask ourselves if the RDA hierarchy **actually matters** (i.e. does this rule matter?) and quite gleefully take Occam's razor to the rest of it.  i think if we called the page "Relationships between rare materials" or "Relationship elements" or something similar, it would be more understandable than using the name of the RDA hierarchy element in this case.

Q. RDA organizes relationship in a deep hierarchy for which the top element is "related RDA entity of RDA entity." In terms of organization/order, would it make sense for DCRMR to follow suit?
i agree with Elizabeth that we can just zoom to the narrow elements we plan for catalogers to use and not worry too much about the hierarchy.  

Here is a follow-up question: 

Do we ever expect that we would need separate pages for inverses?  To do so, seems futile.

**Comment by mjmascaro** [comment]
I do like kalan's [mock up](https://rbms-bsc.github.io/DCRMR/books/other-notes/Related-manifestation-of-RDA-entity/#7.23.5.1) of Related Manifestation of RDA Entity and think its preferable to having separate pages for each element.

As to hierarchy, while I agree we do not necessarily need/want to fully recreate the complexity of RDA hierarchy, I am inclined to group relationship elements by WEMI entity versus lumping them all together.   I think particularly dividing by WEMI will help make the distinction between "issued with" and "bound with" clearer.  Perhaps keeping it as "Related manifestation of RDA Entity" to avoid getting into the granularity of "Related manifestation of manifestation," 
"Related manifestation of item," etc. should work.  

I also think having a broader element would be helpful as a catchall for other relationships that rare materials catalogers may want to record that either do not fit into any of the narrowly defined RDA buckets or do not come up frequently enough to justify a full workup in DCRMR.

**Comment by io-uk** [comment]
The only slight niggle I have with adding several elements on the same page is that the individual element, for instance "Accompanied by manifestation," then wouldn't show up in the table of contents on the left, which users might use to navigate.  You can, of course, find the element if you do a search for that specific element, so it might not matter that much and I might just be overthinking this.

**Comment by lizoknj** [comment]
Iris’s comment about “accompanied by” reminds me that this is a problematic element. The last section of Chapter 5, 5E, is devoted to “accompanying material” (“material issued simultaneously (or nearly so) and intended to be used together [with the publication]”). There are three options for recording “accompanying material”: the first two are to record it in the 300$e,  with or without extent, dimensions, etc., the third is to record it in a note. So “accompanying material”  should be in the  “Order of text” list of physical description elements, and also in wherever we end up putting related manifestations. (Not sure which relationship element it belongs to, as it doesn’t exactly match any of the definitions for these RDA elements—I may post on that separately if I can’t figure it out). 
As for the larger issue of how to treat these related manifestation elements, I am undecided (with every new comment on GitHub,  I change my mind).  Looking forward to the discussion

**Comment by ladylazarus3** [comment]
Hi folks,
Just wanted to send an update from the Belly of the GitHub Whale.  We have total control of the *textual* content of that left-hand navigational pane.  The file that controls the content is [navigation.yml](https://github.com/rbms-bsc/DCRMR/blob/master/_data/navigation.yml)  We can also add links to particular sections of pages.  I've mocked up what the navigation pane looks like with the addition of [the two additions of Reprint of manifestation of and accompanying by manifestation in chapter 7](https://rbms-bsc.github.io/DCRMR/books/preface/).  At that point, the economy saved is having them on the textual content on same page is two less markdown files to deal with and possibly collocating instructions together.

Just for illustrative purposes, we can potentially add the page contents of accompanying material to two different chapter menus, once for chapter 5 (physical description) and another for chapter 7 (other notes), this may or may not be advisable because of the numbering-- which numbering would be reflected in the Markdown file?  Would one entry in the navigational list simply act as a helpful cross-reference?  We could add an instruction to the physical description chapter simply advising catalogers to look elsewhere for accompanying material guidance and provide a link to where that information lives, managing expectation and being helpful librarians.  Regardless, it is possible, but for the sake of keeping the navigational file a manageable size and to keep the organizational structure less confusing, let's keep the # of duplicates low and do this sparingly, if at all.

What we ultimately **do not have control of** in that left-handed navigational pane is a limitation of two levels of structure.  There are parents (in this case, chapter pages) and there are children (in this case, entity and preliminary pages).  There are no grandchildren.  Trying to add grandchildren crashes the whole works (*blushes demurely*  ask how i know :) )  i've added two dashes before the "Reprint of manifestation of" label in the navigational file to make it appear as though there are three levels of content (and this is probably a big **no-no** web accessibility wise).  Also, there is also no built-in ability to make the levels of text in the left-hand navigational plane collapsible.  It is possible someone skilled with java could do this, but that person is not me.  Java hates me and i hate java right back (java started it though).  There have been several requests for this feature addition in the Minimal Mistakes Repo, but the developer (wisely, in my estimation) said something similar which is oddly comforting. :)  Unless we got java-friendly RBMS web folks or in our institutions that want to try their hand at it and implement a sustainable and consistent solution that won't need constant tweaking or headdesk banging, i'd say programming java-friendly collapsible menus aren't a development priority right now.

kalan

**Comment by elizhobart** [comment]
Following discussion in the July 29 meeting, we will pursue creating a separate relationships chapter rather than trying to record relationships as notes. Issued with and bound with were especially highlighted as relationships that will more heavily affect the rare materials cataloging community.

We will use this issue to begin brainstorming how this will work. Questions include: where will this chapter fit in DCRMR? Will relationships be recorded only in this chapter, or will instructions also be included in notes (e.g., 500 note "Translation of ..." to justify 700)?

**Comment by mjmascaro** [comment]
A followup to my comments at today's meeting about some changes that RDA made regarding unstructured descriptions for relationships between WEMI from the pre-3R to post-3R RDA text.

In the Pre-3R text, there are a variety of note formulations given as examples of unstructured descriptions of relationships.  Examples of unstructured descriptions of [related expressions](http://access.rdatoolkit.org/rdachp26_rda26-83.html) include:

- Revised and shortened version of the author’s thesis (Ph.D.)—Yale University, 1982
- Shorter version of the 1969 motion picture of the same name 
- Also issued in other regional editions: Eastern edition; Midwest edition; New England edition; Southwest edition; and Western edition

In post 3R RDA, the one option for recording an unstructured description is to the record the title of the entity you are relating.  So the instructions for recording an unstructured description for [related expression of expression](https://beta.rdatoolkit.org/en-US_ala-458a5896-b879-3c9d-a0d7-065110c3968c/div_xf5_r5n_gdb) is "Record an unstructured description for a related expression as a value of Expression: title of expression."

Therefore none of the note examples above from the previous version of the Toolkit are permissible ways to record this element in the new Toolkit.  

This was a change that Kate James highlighted in the RDA Lab Series.

**Comment by flapka** [comment]
Thanks for this clarification, Michelle. With such a change in RDA, it appears that unstructured descriptions of WEMI relationships, of the type given in your three examples, no longer have an element home. Did Kate suggest where such information might be recorded? Or do others have ideas?

**Comment by elizhobart** [comment]
It occurs to me that issue #20 should also be included in this discussion.

**Comment by mjmascaro** [comment]
@flapka I am afraid, Kate did not give any specific suggestions in the RDA Lab.  I poked around a little in the Beta Toolkit when I was putting together that reply and did not come up with anything obvious.

**Comment by ladylazarus3** [comment]
Is there a rare materials reason we should still record the notes?  Sometimes those MARC 5XX notes, really really give crucial context for the relationship contained in a MARC7XX field.  i would hate to lose that context and it isn't easy to convey with an access point (or relationship element) alone, even though it might be unusual for our descriptive standard, couldn't we retain those notes as a "Note on manifestation" at the very least?  

In so doing we could still:
1. move all relevant relationships to the newly proposed relationships chapter.
1. have separate pages for the entities where instructions for recording those relationships are laid out (e.g. Bound with, Issued with, etc.) within that chapter
1. have a section for "Notes for relationships" on the "Note on manifestation" web page where instructions for recording relationship notes are laid out (e.g. Note on manifestation: 'A reissue of the 1756 ed., without the plates', Note on manifestation: 'Maps in pocket on inside back cover.'

That way, we are using the Accompanied by, Reprint of manifestation of as intended, but still have that important explanatory context associated with the bibliographic description of why that relationship exists.

i can make a mock up of this and deploy it to the DCRMR webpage if folks want to pursue it further.

kalan

**Comment by flapka** [comment]
I think I more or less agree with @ladylazarus3. If the cataloger intends only to state the relationship, without added context or justification, then there's probably no good reason to use anything other than a full access point, identifier, or URI. 

Where further elaboration is required, use note on work, note on expression, note on manifestation, or note on item (or item-specific modification?).

**Comment by lizoknj** [comment]
As noted earlier within this thread, it is difficult to identify a RDA2 element that fits “accompanying material”.  DCRM1 treats accompanying material, defined as “material issued simultaneously (or nearly so) and intended to be used together [with the publication]”, as physical description. It appears in its own section (5E) at the end of Chapter 5. Three options are given for recording “accompanying material”: the first two are to record it in the 300$e,  with or without extent, dimensions, etc., the third is to record it in a note. 7B11 contains instructions for describing accompanying material in a note.

The first two options are not found in RDA1. In the RDA1 mapping of AACR to RDA1, the AACR instructions for accompanying material, 15E, are mapped to 27.1.1.3, Recording Relationship to Related Manifestation. (Though, interestingly,  none of the examples given under 27.1 bear any resemblance to “accompanying material”, as described in AACR or DCRM1). Similarly, the MARC to RDA1 mapping for 300$e is to 27.1. Reflecting this change, the RBMS PS located DCRM1 instructions and examples for “accompanying material” to RDA Chapter 27.

Whether we decide to create separate documents for the various types of related manifestations, or put them all in a single chapter, it would be desirable to identify the relationship type. Reviewing the RDA2 definitions of various elements/manifestation relationships between manifestation, I don’t find one that fits “accompanying material”.

“Accompanied by manifestation: A manifestation that is issued with another manifestation, without any relationship to its content.” [Accompanying material as used in AACR/DCRM1 does refer to the content of the main manifestation, so this doesn’t work.]

“Issued with: A manifestation that is issued on the same carrier as a manifestation being described.”  [Accompanying material is not on the same carrier as the main manifestation; in some cases, e.g. atlases or a reference guide to a CD set, it is a different carrier unit type]

“Supplementary content:  An indication of content that updates or complements the primary content of an expression.” [This is closer to what accompanying material is, but it is expression-level; and all the examples of supplementary content given involve material that is physically part of the  main resource”.]

I have also toyed with the idea of continuing to treat accompanying material as just an additional physical component of the resource, which would mean (I guess) including it in extent, but that has its own drawbacks. Can anyone else suggest where to put this troublesome data element, or should we just park it in Note on manifestation, as Francis suggests above (in a broader context).

**Comment by elizhobart** [comment]
After reviewing this issue and yesterday's discussion, here's what I'm currently thinking:

1. Create a new "Note on expression" page to house instructions relating to expression-level elements. I'd propose placing it right after "Note on manifestation" in our order of text.
2. Use unstructured notes for relationships described in 7B2.1 and 7B7.2 in "Note on expression" or "Note on manifestation," as appropriate. Remove the Related manifestation of RDA entity" page.
3. Leave bound-with and issued-with in their current locations.
4. Accompanying materials is a tough one. I'm leaning toward adding a new element page for [accompanied by manifestation](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-c700044a-97ee-3f4b-8ac3-2139c2e827ca&highlight=accompanied) for these instructions. Like Iris, I think catalogers may look for this instruction on the left-hand navigation, so I think it's worth having this on its own page.
5. Hold off on developing any chapter or appendix on relationships for the time being. Following conversations yesterday, I'm inclined to wait until we have a better sense of what other guidance may be available. We may not need this at all. We also might, but I think we can wait to find out.

Does this make sense?

**Comment by ladylazarus3** [comment]
Hey there,

i think this approach makes sense-- it gets catalogers the practical instructions they need in a spot where they expect to find them, complies with our original mandate to reorder the DCRM(B) text to align with the RDA element set while it also reduces complexity and ensures a manageable editorial workload.  To use a favorite phrase, this is a very sleek solution indeed. :)

i'm happy to make the changes to the [navigation.yaml](https://github.com/rbms-bsc/DCRMR/blob/master/_data/navigation.yml) to match the [Order of the Text spreadsheet](https://docs.google.com/spreadsheets/d/1nP4uJPxj6gbfWPcPusKxAqxBXbQW9HG8uoU1SxZMqq0/edit) after the spreadsheet changes are made.  i try to double-check the spreadsheet and the left-hand navigation pane are in sync semi-regularly, but if i miss something or make a mistake please don't hesitate to let me know.

kalan

**Comment by lizoknj** [comment]
I'm fine with all these points. No. 4 (accompanying material) is the most problematic for me, because the RDA definition for "accompanied by" does not fit what AACR called "accompanying material", since it describes the content of the manifestations as unrelated. But I don't see an alternative (for the present) to using "accompanied by", because the concept of "accompanying material" as formerly defined seems to have dropped out of RDA entirely. 

The only reference I could find to what I would think of as accompanying material is in the document named "Aggregates" in the Guidance section 
(https://beta.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-bd1f1ef9-978c-34ee-8881-acc1500130b9):
"Augmentation aggregate
An augmentation aggregate is a manifestation that embodies two or more expressions of two or
more works, where one work is supplemented by one or more other works.
Each expression of an augmenting work supplements the expression of the augmented work
without affecting its integrity or changing its content.
Examples include a volume that embodies a novel and a foreword, illustrations, an index, etc., a
CD that embodies a software program and an accompanying book with instructions on using the
software, a DVD that embodies a motion picture and bonus material about the making of the
motion picture."

(The CD plus instruction book is actually two carriers--it would parallel the situation where you have an atlas and a volume of text. In other instances, the carrier type of the accompanying/augmenting resource is the same. )

This seems to be another case of RDA not yet having caught up to the changes made to the original product. Though this is even worse--with aggregates we seem to be descending into the fever swamps of cataloging theory and practice.  Hopefully, voices will be heard in the larger cataloging community on this and other issues.  

Until then, I guess "accompanied by" will work for "accompanying material". Do you want me to create the element, since I have the most immediate need for it? I will park the instructions from 5E there, and create a reference to the "accompanied by" element from the physical description chapter--I guess it should be made at the highest level, where we have the prescribed punctuation and sources of information for the chapter as a whole (but I defer to the keepers of the text on structural matters).

**Comment by elizhobart** [comment]
Thanks for the feedback, kalan and Liz! Liz, I agree that accompanying material is the most problematic, for the reasons you mentioned. In addition, I'd been thinking of "accompanied by manifestation" as mapping to DCRM(B) 7B11 and hadn't properly considered the relationship to 5E! 

We could shortcut the whole issue and just map accompanying material (7B11) also to "Note on manifestation," although it would make it somewhat harder to find as it would no longer appear in the left-hand navigation. Or we could continue to map it to "accompanied by," even if not fully RDA-precise. 

For the instructions at 5E, part of the issue is that RDA considers the physical description of accompanying material to be additional physical description statements. Maybe for 5E we could add a section to the physical description chapter for accompanying material that would map to the relevant RDA elements, but still bring the instructions together in one place in our text?

**Comment by lizoknj** [comment]
After working within the separate elements for so long, I'd lost touch with the eventual goal of bringing the instructions  back together into a unified set of guidelines. So I like your idea of restoring "accompanying material" to the physical desc chapter, while mapping the instructions to the relevant RDA elements. I think current DCRM users will look for these instructions under physical description out of long habit, while new users will find it a reasonable placement, since accompanying material represents a separate physical unit which should be accounted for in the description of the resource.

**Comment by lizoknj** [comment]
I created a new Google document in the Other Notes chapter for “Accompanied by manifestation”, and put the basic instructions for recording accompanying material there, as an unstructured note, with see references to the relevant elements in physical description for how to describe the extent, illustrative and colour content, and dimensions of the accompanying material.
Not sure about this, because, a) the definition of the RDA element does not match what AACR/DCRM called “accompanying material”, which does consist of related content (I altered the definition);  and b) the RDA element assumes that there will be a separate description for the accompanying material. Since accompanying material is generally bibliographically insignificant (e.g. a price list, a subscriber’s list, a little booklet, a map), few will want to do this (I made it optional). I can’t help wondering whether the Accompanied by manifestation element was not written for “accompanying material”, which just slipped through the cracks during the rule-making process. It seems suspicious that the Beta Toolkit provides no mapping of MARC 300 $e to an equivalent RDA element. If  anybody can come up with a better solution, I will be delighted.

**Comment by ladylazarus3** [comment]
i followed the guidance from @elizhobart (quoted below) and took a crack at the md file for [Note on expression](https://rbms-bsc.github.io/DCRMR/other-notes/Note-on-expression/), but followed the order outlined in GitHub issue #89 about the organization of the notes by WEMI stack in the new proposed Additional notes chapter.  Along with the [Note on Manifestation](https://rbms-bsc.github.io/DCRMR/other-notes/Note-on-manifestation/), and other "Note on..." elements, did we catch and resolve most of the pieces here?

kalan

> After reviewing this issue and yesterday's discussion, here's what I'm currently thinking:
> 
> 1. Create a new "Note on expression" page to house instructions relating to expression-level elements. I'd propose placing it right after "Note on manifestation" in our order of text.
> 2. Use unstructured notes for relationships described in 7B2.1 and 7B7.2 in "Note on expression" or "Note on manifestation," as appropriate. Remove the Related manifestation of RDA entity" page.
> 3. Leave bound-with and issued-with in their current locations.
> 4. Accompanying materials is a tough one. I'm leaning toward adding a new element page for [accompanied by manifestation](https://beta.rdatoolkit.org/Content/Index?externalId=en-US_ala-c700044a-97ee-3f4b-8ac3-2139c2e827ca&highlight=accompanied) for these instructions. Like Iris, I think catalogers may look for this instruction on the left-hand navigation, so I think it's worth having this on its own page.
> 5. Hold off on developing any chapter or appendix on relationships for the time being. Following conversations yesterday, I'm inclined to wait until we have a better sense of what other guidance may be available. We may not need this at all. We also might, but I think we can wait to find out.

**Comment by dcrmr** [comment]
Since this issue hasn't had any discussion since September 25 and we've now substantially restructured the Notes chapter, I'm going to mark this as closed.
