### ISSUE TITLE
Defining Color Content 

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#33]
The RDA definition of “color content” and the RDA vocabulary for this element differ considerably from the definition and terminology used in AACR and DCRM1. There are actually two areas of difference: the meaning of “color”; and whether color content should be recorded only for illustration or for the entire resource. I’ve looked at the RBMS PS 7.17 for color content, but I’m not sure how it defines color, or whether it considers that non-illustrative content has color content. Hoping for help from the group. 

Here is some background:

RDA1 7.17.1.1 (expression level) ((https://docs.google.com/document/d/1pSRDMM2r2LwmStGxA1-MQ7jL-hXt7uNujHnklSXume0/edit)
"Colour content is the presence of colour, tone, etc., in the content of a resource. Black, white, single colour shades of black, single colour tints of white, and single colour tones of gray are considered to be single colours."

RDA2 Colour content (manifestation level)
(https://beta.rdatoolkit.org/en-US_ala-26e5e1f2-b7fb-383b-954a-b2560eb6eb40/05f869f7-2850-4f7a-ad51-8e318629d64c)
“Definition and scope: An indication of the presence of colour, tone, etc., embodied by a manifestation. Black, white, single colour shades of black, single colour tints of white, and single colour tones of gray are considered to be single colours. Colour content applies to an expression with a content type of "cartographic image", "cartographic moving image", "cartographic three-dimensional form", "notated movement", "notated music", "performed movement", "still image", "text", "three-dimensional moving image", "three-dimensional form", or "two-dimensional moving image".

Having defined color in a somewhat non-intuitive manner (is there any manifestation that would NOT have “colour content”, according to this definition?), RDA offers two controlled terms for use in this element: "monochrome" and "polychrome".

"monochrome (https://beta.rdatoolkit.org/Glossary?externalId=en-US_rdaregistry.info-termList-RDAColourContent-1002&highlight=monochrome) A colour content that consists of tones of one colour, or black and white, or black or white and another colour."

"polychrome (https://beta.rdatoolkit.org/Glossary?externalId=en-US_rdacc1003&highlight=polychrome ) 
A colour content that consists of two colours, neither of which is black or white, or more than two colours."

(there are also options to use terms from alternate vocabularies, or just make up your own terms)

Neither term is very user-friendly, and the terms don’t line up with the way DCRM1 describes color, which is based on the AACR definition of “colour illustration”:

"An illustration containing any colour; black, white, and shades of grey are not to be considered colours."

Like AACR, DCRM1 discusses color mainly in the context of illustration:

"5C3. Color illustrations
5C3.1. Describe color illustrations as such using the abbreviation “col.” Treat illustrations printed with a tint block (e.g., chiaroscuro woodcuts, tinted lithographs) as color illustrations.
: col. ill.
: ill., col. maps, ports. (some col.)
: ill. (some col.), maps, plans
: col. ill. (Baxter prints)

5C3.2. Do not describe hand-colored illustrations as “col.” unless there is evidence that the publication was issued with the hand coloring. In case of doubt, consider any machine-press publication with hand coloring to have been issued that way by the publisher. Always mention publisher-issued hand coloring in a note (see 7B10.3); make a local note on the presence of other hand coloring if considered important (see 7B19.1.3).
: col. ill.
Note: With hand-colored wood engravings 
(Comment: Title contains statement “with colored engravings”)
: col. ill. (lithographs)
Note: Lithographs are hand colored, as issued; see Sitwell, S. Fine bird books, p. 78

5C3.3. If both the text and illustrations are printed in a single color, do not describe the illustrations as “col.” Make a note to indicate the color of the ink if considered important.
: ill.
Optional note: Printed in green throughout"

The table below makes it plain that RDA’s definition of “color content” is far more expansive than AACR’s (for books) and DCRM1’s:

Monochrome					RDA		AACR		DCRM

Tones of black or white or grey	        Y		N		        N
Tones of e.g. red				Y		Y		        N
Black and white				Y		N		        N
Black or white and e.g. red	        Y		Y		        Y

Polychrome					RDA		AACR		DCRM
2 colors (neither black
 or white)					        Y		Y		        Y
More than 2 colors			        Y		Y		        Y

Adopting the RDA definition and vocabulary for color content would represent a major departure from previous practice for DCRM. The RBMS PS on color content seems to punt on the issue. Although it doesn’t explicitly dissent from the RDA definition of color, it rejects the RDA terms “monochrome” and “polychrome”. Instead, it accepts the RDA alternative, “Record the colour content by using one or more terms from a substitute vocabulary (see 0.12),” and refers users to LC-PCC PS 7.17.1.3: “If recording colour content, generally use a substitute term (e.g., color), or record a phrase such as "some color" or "chiefly color" as details of colour content (see 7.17.1.4).”

If "color" is the term we want to use, we would want to be sure that the alternative vocabulary defines the term in an acceptable way. The LC Vocabulary for Color Content (http://id.loc.gov/vocabulary/mcolor.html) seems like a good candidate for alternative terms.  Here are the terms within this vocabulary, and their definitions:

“black and white:	Resource is printed or executed in black-and-white [monochrome is listed as a variant term]

color:			Resource is printed or executed in more than one color [polychrome is listed as a variant term]

gray scale:		Resource is produced with degrees of dark to light from black to gray to white

hand colored:	Resource image, produced by a printing or photographic process, is hand colored

mixed color:		Collection is a combination of one color, black and white, multicolored, and/or hand colored resources

one color:		Resource is printed or executed in a single color”

The LC terms and definitions for “color” and “black and white” (which the PS recommends for still images, if considered important for identification) would match DCRM1 practice. Should DCRMR recommend using the LC Vocabulary specifically?  And should a definition of color content that matches DCRMR practice be substituted for the RDA Definition and Scope (if this is what we want to do)?

I am running out of steam so will defer the discussion of whether “color” takes in color of base and applied materials for non-illustrative matter.

**Comment by ladylazarus3** [comment]
i suppose we don't *have* to have folks record color content as a structured description, although it might be nice to do it that way.  if we *do* decide that a structured description and a controlled list is the way to go, i agree that [LC's list](http://id.loc.gov/vocabulary/mcolor.html) is as close to the mark as we are going to get.  Although i've always really liked using qualifiers like "chiefly" etc.  as it really gives an expectation of what one is about to see.  

Another benefit of an unstructured description here is that sometimes we've elaborated on how the illustrations have been created "ill. (engravings)" which wouldn't be in any sort of controlled vocabulary and couldn't necessarily be included as an RDA "details of colour content" because it isn't technically about color--  where a note like, "Title page in red and black" and the information about issued with hand-coloring might be more appropriate to be included there.  *sigh*

My curators always always always want more information about illustrations than less.  so i tend to make lots of notes about illustrations because they always want to be able to find the "pretty" books later.  i guess i worry that a structured description just might not get us there.

**Comment by flapka** [comment]
If we offer DCRMR guidance to fulfill the "structured description" path of color content, such guidance cannot (I think) use the LC vocabulary because half of the terms in it extend beyond the scope of that path (which is limited to specifying whether something is monochrome or polychrome).

**Comment by lizoknj** [comment]
I didn't interpret the RDA color content instructions for structured description of color content to mean that we could use only a term that conforms to the RDA division of the world of color into two categories: monochrome and polychrome. I took the option to  "Record a term from another suitable vocabulary encoding scheme"  to mean that we could use a term from another vocabulary, even one such as the LC vocabulary that makes more subtle (and, to my mind, more reasonable) distinctions between various gradations of color. But I will admit that my brain shuts down after about ten minutes of any discussion of what is color and what is not.

**Comment by elizhobart** [comment]
I agree with your reading, Liz. Option 2 under structured description allows use of another vocabulary encoding scheme, with an example from AMIM. I believe that this allows us to use a controlled vocabulary other than the options provided by RDA. My preference, I think, is to use structured description with the terms from the LC list, although I do also hear kalan's point about unstructured description giving us the flexibility to use terms like "chiefly color," which doesn't seem to be an option with LC.

**Comment by lizoknj** [comment]
I agree that "chiefly col." is a valuable piece of information. But the RDA reworking of the scope of color content to refer to the whole manifestation, not just to the illustrations, would create problems with using information about illustrations  in a color content element.   If there were a way in RDA to specify which portions of the resource had color content (an equivalent of the MARC $3, which is valid in the 340, so you could do 340 $3 illustrations$gcolor), that would help. But as things are, I think you would have to put "color" in color content, and and "illustration" in illustrative content, and then put the two things together in the "details of" elements--oh wait, they are softly deprecated--I mean the note on manifestation.

**Comment by flapka** [comment]
I suppose my suggestion that RDA defines the structured path quite narrowly -- as only color / black & white (polychome / monochrome) is in part based on the precedent set in RDA Classic, where even single (structured-looking) terms such as gray scale (which is on the LC list) and sepia are included in the examples for *Details of colour content* (which maps to the unstructured path of Colour content?).

At the end of the day, I'm mostly indifferent. It is rather preposterous that the element reference for Colour content declares that MARC 300 $b should be used for structured descriptions, considering the mess of legacy data already entrenched in that field.

**Comment by lizoknj** [comment]
Agree that the element reference saying use MARC 300$b for structured descriptions is ridiculous--unless it is mentioning 300$b just to accommodate legacy data. In the ARLIS CAC proposal to define a subfield in $340$g for color content, we said that the 300$b could be used for unstructured description of color content, while 340$g would be used for structured/controlled description. 

Do you think we could use the Color Content element as a replacement for the softly deprecated Details of color content element? I thought it was an either/or choice for the four-fold path (four paths diverged in the RDA wood ...) If we are allowed to use both a  controlled term structured description (340$g) AND an unstructured description (300$b/500, whatever...), that would be fabulous. I was thinking all these softly deprecated details of elements pertaining to manifestation would have to go in the Note on manifestation, turning it into the equivalent of the spare bedroom where you put all the junk you haven't got around to finding an appropriate home for.

**Comment by io-uk** [comment]
According to Gordon Dunsire's document of December 2019 entitled _[RDA content elements](http://www.rda-rsc.org/sites/all/files/RDA%20Content%20elements%20followup.pdf)_ (where he recommends to remove the element "Details of colour content" from RDA,) he states on p. 10 that the new element "colour"  "partially subsumes Expression: details of colour content. The remaining scope of the deprecated element is subsumed as an unstructured description of Manifestation: colour content".  I think this answers Liz's question. 
I really don't see why MARC 300$b should only be used for structured descriptions from now on.

**Comment by mjmascaro** [comment]
Some thoughts...

- I agree with Liz's and Elizabeth's interpretation that the option "Record a term from another suitable vocabulary encoding scheme" does allow us to use terms another vocabulary such as the LC list.  This option was also in RDA classic (as an alternative), and the LC-PCC PS used it as justification for continuing AACR2 practices for recording color.  
-I believe that it was the RSC's intent that deprecated "details of ..." elements would map to unstructured description option within their "parent" (for lack of better term) element.   
-As to the mapping of 300 $b as a structured description, per the Post 3R RDA Toolkit, "structured note" is a form of structured description, and you can kind of make the argument that past practice for the 300 $b is more of a structured note, since how that field has been recorded is fairly formulaic.  That said, I totally agree with Francis that due to the wide variety of legacy data (and multiple elements) recorded in the 300 $b, it does not serve the purpose intended for a structured description and the 340 $g is a preferable field for recording structured description of color content.
-I do not see why a metadata description set could not repeat an element using different recording methods, so I am not sure we have to pick an either or approach here.  If group consensus is that 300 $b should be viewed as a unstructured description, there can be instructions for continuing DCRM(B) practice as an unstructured description (300 $b) and optional structured description using LC term list (340 $g).  In addition, also including instructions for any notes related color content as an unstructured description (500).

**Comment by ladylazarus3** [comment]
one last thought from me... if none of the external lists are good enough
for rare materials purposes, would it hurt to connect with the CVEG folks
and see if there is a CVEG color content facet that could be further
developed for our own needs?

**Comment by elizhobart** [comment]
Thanks for the discussion, everyone. I think you all make good points regarding structured/unstructured description and encoding in 340 $g vs. 300 $b. With all this in mind, my druthers would be:

*Use LC as the controlled vocabulary (I think you raise an interesting idea, kalan, but at this juncture, I'd rather use a preexisting vocabulary rather than ask CVEG about possible further developments)
*Use unstructured description in 300 $b, which allows constructions we're used to
*Provide an optional instruction to add a structured description in 340 $g
*Additional unstructured notes can be recorded in 500 fields

**Comment by elizhobart** [comment]
Decision in July 29 meeting to use my suggestion above, omitting MARC coding. We feel this would still be important to incorporate, but may go into an application profile later. I will move MARC coding to the "future work" issue.
