### ISSUE TITLE
Alternative rule or exceptions

### ISSUE THREAD

**Issue by mjmascaro** [rbms-bsc/DCRMR#34]
In the RBMS PS alternative rules, such as DCRM(B) 2B3.2 related creating separate bibliographic descriptions for an individual impression, state, binding variant, or copy within a single edition or issue, were called "exceptions" to match the Pre 3R RDA terminology.  Exception does not appear in the Post 3R RDA.  

Which terminology should be used in DCRMR?

I vote for "alternative rule," since it is clearer than "exception."

**Comment by mjmascaro** [comment]
This question came up in [Designation of Edition](https://docs.google.com/document/d/1RdsSOlT6xC6qTydK7dJvNiZUxUFYXDeUPFbe3a_u-zQ/edit#bookmark=id.cpdnbfcn5cvp)

**Comment by ladylazarus3** [comment]
i also prefer to use 'alternative rule' in these cases.  i think that is clearer than exception.  In the experimentation of chapter 4, we used "alternative rule" as a section heading of [Date of manufacture](https://rbms-bsc.github.io/DCRMR/books/ppdm/Date-of-manufacture/#42254-alternative-rule) to mirror the language of DCRM(B) 4G (in the pdf page 100) and *alternately* in italics  to start off the instruction at {4.225.4.1](https://rbms-bsc.github.io/DCRMR/books/ppdm/Date-of-manufacture/#4.225.4.1), we can always tweak it.

Whatever we decide to use, it might be good to document our decision within the [Examples and notes}(https://rbms-bsc.github.io/DCRMR/books/introduction/Examples-and-notes/) section of the introduction to be consistent going forward as well as being a helpful explanation for folks using the text.  (compare with VIII.2 Notes on page 19-20 in DCRM(B) pdf

**Comment by elizhobart** [comment]
In the preliminaries group, the term "alternatively" was suggested. This would be good to discuss with the whole group and come to a consistent decision. In addition, we may also want to give some thought to how these display in GitHub (and perhaps if it would be possible to filter to alternative rules?) since they need to be applied uniformly.

**Comment by flapka** [comment]
Section IV of the DCRM(B) has the following:

• "Alternative rule" designates an alternative option which affects all or several areas of the description, and which must be used consistently throughout. In DCRM(B), alternative rules apply to the transcription of original punctuation and to the creation of separate records for individual impressions, states, binding variants, or copies.
• “Optionally” introduces an alternative treatment of an element.
• “If considered important” indicates that more information may be added in a note, and thus signals choices for more or less depth in the description. This phrase covers the entire range between best practice on the one end, and highly specialized practices on the other.

Are we proposing to use "Alternative rule" and "Optionally" (or "Option") in the same sense as DCRMB? That is, are we maintaining these as separate concepts, where RDA no longer uses "Exception"/"Alternative rule"? This would be my preference, reverting to alignment with the old DCRMB terminology.

**Comment by ladylazarus3** [comment]
Folks, apologies for my confusion on sections [viii - examples and notes](https://docs.google.com/document/d/1biJnOVVuNlJ5PnVq3-saJnKg8p2HYo_aXij1aA8lcOM/edit) and [iv - options](https://docs.google.com/document/d/1ReY2K3Y9XOKy26a7rRwp6bQnBlA17fGMokWnjoy8zsE/edit) from my comment above. 

It had been a little bit since i reviewed the prelims! :)  i agree and this is my preference too.

**Comment by lizoknj** [comment]
Agree with using "Alternative rule" and "Optionally" (better than "Option", which means something different in RDAspeak)

**Comment by ladylazarus3** [comment]
i agree too and have nothing really further to add to this one, but, i did want to make a plug for the [built-in Algolia search feature](https://rbms-bsc.github.io/DCRMR/Search/) that allows full text searching of the GitHub hosted web site.  

It as more and more pages are populated and need potential fine-grained wordsmithing-- this built-in search feature can be an easy way to find keywords that need changing (e.g. type in "Alternatively" to the search box).  My question is: are folks okay with going and finding the Markdown file in the [pages folder](https://github.com/rbms-bsc/DCRMR/tree/master/_pages), making the wordsmithing changes, and submitting those changes as a pull request?  Otherwise, we could start a "Wordsmithing" issue thread that folks can report needed changes without making those changes themselves.  i think either way will work, but similiarly to the [404 issue thread](https://github.com/rbms-bsc/DCRMR/issues/26) we may want to collocate these sorts of changes together in a single GitHub issue.

Thoughts?

kalan

**Comment by elizhobart** [comment]
Let's start a "Wordsmithing" issue thread for now. I suspect more and more of these issues will arise as we continue editing, so this will let us put them all in one place. I would be somewhat hesitant to do a pull request for wordsmithing changes right now, since we're still in the process of finalizing elements. Some wordsmithing will be changes in practice that we decided during this phase. Some will be longer editorial changes that have been overlooked ("publication" has a bad habit of sneaking in). I think better to do it once at the end.

**Comment by elizhobart** [comment]
Decision in July 29 meeting: retain terminology from DCRM(B). Wordsmithing issue has been created (#48 ). kalan will use search to update files once everything is done. For elements that are still being finalized, this change can be made now.
