### ISSUE TITLE
Signatures: Hebrew and other nonroman alphabetical and numeric sequences

### ISSUE THREAD

**Issue by lizoknj** [rbms-bsc/DCRMR#45]
The note on extent of manifestation element (https://docs.google.com/document/d/1iNg8ZqkldcfaDVJ_lhlYeyQPUkmuHi2smaInRf1oxZI/edit#)  contains notes on signatures. Francis and Jessica commented that we should consider rewording the sections on Hebrew and other nonroman alphabetic and numeric sequences to reflect the feedback on this issue on DCRM-L (https://listserver.lib.byu.edu/pipermail/dcrm-l/2018-May/005474.html), either replacing current DCRM practice, or as an alternative. I meekly agreed, but confess that coming up new rewording is utterly beyond me, so I am passing the torch on to my betters.

**Comment by elizhobart** [comment]
I am coming up empty, too. Maybe we should get feedback from people with more Hebrew knowledge? I have none, myself.

**Comment by elizhobart** [comment]
Quick update: I reached out to Matthew H. about this. At a glance, he thinks our drafted language looks good as is, but will give it some additional thought and let us know if he has any suggestions.

**Comment by elizhobart** [comment]
I received a very helpful reply! The full version is fairly long, so I will summarize his recommended changes and brief notes: 
<ul>
<li>In the first and fourth examples, change "Hebrew characters" to "Hebrew numerals". Notes: "If we are assuming numeric sequence, then I think it's clearer to use the word "numerals" instead of characters here. But if we are making no such assumption in ambiguous or doubtful cases, then "characters" might be a better word."</li>
<li>Append to 5.201.4.8 (Nonroman signatures (alphabetic sequence)): "If considered important for clarity, follow a compressed signature statement by a total count of the gatherings in that sequence in square brackets." He also suggests adding examples: 
<ul>
<li>Signatures: pi1 α-γ^2 Α-2Λ^2</li>
or
 <li>Signatures (in Greek characters): pi1 a-g^2 A-2L^2</li>
<li>Signatures: [aleph]-[shin]^8, a-k^8 </li>
or 
<li>Signatures: ʼ-sh^8 (in Hebrew alphabet), a-k^8</li>
(Comment: Indicates a Hebrew alphabetic sequence followed by a roman sequence)
<li>Signatures (in Church Slavic alphabet): A-Ẏ^2 [=41], 2A-2Ẏ^2 [=41], 3A3ŌT͡^2 [=24]</li>
(Matthew also recommends restoring examples of alphabetic sequences from DCRM(B) here)
</ul></li>
<li>Add instruction: "<b>Directionality of sequence</b>. Include in the note an indication of the direction of a sequence, if it does not follow the reading direction of the script or text in that sequence, if there are sequences in opposite directions in the same resource, or if the directionality of the sequence is otherwise ambiguous or unusual.
<ul>
<li>Signatures (right to left): ):(⁸ A-2Y⁸. (Source: Hebrew grammar printed in Basel (https://clio.columbia.edu/catalog/13431762).</li>
</ul>
</li>
</ul>

</ul>

Matthew also offered to help identify additional examples and run this by other colleagues.

My recommendation would be to implement the changes Matthew suggested. Amy and kalan, if it would be helpful, I can forward you his email, which would likely be more legible than my bulleted list. I'd also like to take him up on his offer of broader feedback. This is expertise we don't have within our group and seems like an excellent opportunity to internationalize the standard.

**Comment by ladylazarus3** [comment]
Whoa!  This is extremely helpful!  Thanks @elizhobart for reaching out to Matthew.  Yes, please do forward the email.  

i can make the necessary changes to [Note on extent of manifestation](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/) ([5.201.4.7](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/#5.201.4.7) and [5.201.4.91](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/#5.201.4.91), etc.) and post the link to this Github issue thread when those changes are ready for review.  Does that sound like a good work plan to folks?  That should get us closer to resolving this issue thread.

i'm on-site at the library the rest of this week, so probably looking at Sept 16th for those changes at the very earliest.

kalan

**Comment by elizhobart** [comment]
@ladylazarus3, the email has been forwarded! That plan sounds good to me.

**Comment by ladylazarus3** [comment]
Hey there folks,

Here is [Note on extent of manifestation w/additions](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation-MHadditions/).   i included a "(see 5.201.4.93)." within [5.204.4.8](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation-MHadditions/#5.201.4.8) because MH's additions introduce compressed signatures before [5.201.4.93](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation-MHadditions/#5.201.4.93).

1)  Does this look good / meet expectations / incorporate all the helpful additions correctly?

Secondly, many of the superscripts now are displaying correctly in GitHub Markdown. However, GitHub markdown "very helpfully" flipped the text-orientation the superscript 8 of this example (screen shot below with DCRMB4 and DCRMR text side-by-side and i cannot (for the life of me) get it to "un-flip".  if all else fails, i will include the screencap on the webpage.  

<img width="330" alt="flipped8" src="https://user-images.githubusercontent.com/16126044/93511073-d2715d00-f8e7-11ea-9534-29b48dd1ba5c.png">

2) i just wanted to confirm A-Ẏ2 [=41], 2A-2Ẏ2 [=41], 3A3ŌT͡2 [=24] does not include superscripts?  (it caught my eye when i was ungarbling what GitHub did to the other superscripts and wanted to double-check).

Please check over this file: [Note on extent of manifestation w/additions](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation-MHadditions/) page and please don't be shy if i (or GitHub) has garbled some of the special characters unintentionally.   

kalan

**Comment by elizhobart** [comment]
Sorry for the delay, kalan. Somehow, this completely slipped by me! My apologies for not catching this sooner. Unfortunately, it looks like this is missing a number of superscripts. I think anywhere that Matthew used a ^ he was indicating the need for a superscript, so A-Ẏ^2 [=41], 2A-2Ẏ^2 [=41], 3A3ŌT͡^2 [=24] should be A-Ẏ<sup>2</sup> [=41], 2A-2Ẏ<sup>2</sup> [=41], 3A3ŌT͡<sup>2</sup> [=24]. Sorry for the confusion!

**Comment by elizhobart** [comment]
Some additional information from Matthew regarding Arabic script:

Since there's not the same concern about ambiguity between letters and numbers in Arabic script, I think the rules suffice without making additional exceptions. I assume Hindu-Arabic numerals would just be converted to western arabic numerals, so possibly this could be indicated in the note: ("Signatures (in Hindu-Arabic numerals): 1-12<sup>8</sup>" or something to that effect.)

Maybe we could add that to one of the example blocks. Otherwise, I think this section is ready to go.

**Comment by ladylazarus3** [comment]
Thank you for checking this over and for the additional comments.

i understand the use of carrots to designate superscripts, i just wanted to double-check specifically regarding the Church Slavic example because they are not superscript in the DCRM(B) text for the 'Signatures (in Church Slavic characters)' portion.  i've added the extra Hindu-Arabic numeral example to [5.201.4.7](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/#5.201.4.7) and superscripted the Church Slavic alphabet examples in [5.201.4.8](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/#5.201.4.8) and [5.201.4.93](https://rbms-bsc.github.io/DCRMR/phys-desc/Note-on-extent-of-manifestation/#5.201.4.93).

i've pushed those changes out to deployment and changed "Note-on-extent-of-manifestation-MHadditions" to "Note-on-extent-of-manifestation." so folks will find the the content at the 'normal' URL now.

Thanks and let me know if anything else needs tweaking.
