### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by elizhobart** [rbms-bsc/DCRMR#54]
A question was raised in our August 12 meeting about fonts. As yet, we have not selected a font for the main text DCRMR and previously discussed using Courier for examples. Courier can be visually unclear, as it is a monospace font.

Questions:

1. Should we prefer serif or sans serif fonts? Or perhaps a mix (e.g., serif for main text and sans serif for examples)?
2. Any thoughts on specific fonts?

**Comment by ladylazarus3** [comment]
Hi folks, 

Just for reference, i wanted to link the two most common places you'll see font settings for DCRMR.  They are [here](https://github.com/rbms-bsc/DCRMR/blob/master/_sass/minimal-mistakes/_base.scss) and [here](https://github.com/rbms-bsc/DCRMR/blob/master/_sass/minimal-mistakes/_variables.scss).

Right now, the serif font is "Palatino Linotype" and the monospace is "Courier New." but we can change them to a different web-safe font as needed.

kalan

**Comment by flapka** [comment]
1. I rather prefer a mix: serif for guidance, sans-serif for examples. 

2. For guidance, the current font (Palatino Linotype) looks nice. For examples, I don't have a favorite sans-serif, but Helvetica at least is associated with an entertaining documentary (http://www.documentarymania.com/player.php?title=Helvetica)

**Comment by ladylazarus3** [comment]
Here is a picture of the Date of publication examples in Helvetica.  (i have to watch that documentary, Francis! :) )   Honestly, picking out fonts is really not my thing and i'm so grateful for the discussion.

![sanserif](https://user-images.githubusercontent.com/16126044/90058711-b73b7e00-dca7-11ea-9425-aa7a97da6a2d.jpg)

**Comment by deborahjleslie** [comment]
I do like Palatino Linotype for print, but would recommend either Georgia or Lora, serif fonts both designed for screen readability. 

San serif is a real problem, as the chronogram example illustrates so perfectly. Thanks for using it, kalan! If you can find a san serif that clearly distinguishes between 'I' and 'l', that would be worth considering. Otherwise, as in the previous sentence, you won't know that the first I is an uppercase 'eye' and the second is a lowercase 'ell'.

**Comment by deborahjleslie** [comment]
Now that I think about it, we chose Courier New for example text _precisely_ because it was monospace. I like the idea of similar but different typefaces for the new product. Maybe we can consider some monospace fonts designed for the screen, such as the open source [Inconsolata ](https://en.wikipedia.org/wiki/Inconsolata)

**Comment by ladylazarus3** [comment]
@deborahjleslie Absolutely!  :)  Here is a screen capture of that same instruction with Georgia as the serif font and Inconsolata as the monospace font for the examples.  i think gravitating towards open source fonts speaks to a very DCRMR-esque spirit.  Thanks again for all the feedback, folks. ❤️ ❤️ ❤️   Keep 'em coming! :) :) 
kalan

<img width="709" alt="Georgia and inconsolata2" src="https://user-images.githubusercontent.com/16126044/90186548-ed4b3180-dd7d-11ea-8726-feae71d0289f.png">

**Comment by ladylazarus3** [comment]
For comparason, although the differences are subtle, here is a screen capture of the Lora serif font for instructions and the Inconsolata as the monospace font for the examples for folk's comparison. 

<img width="713" alt="Lora and inconsolata" src="https://user-images.githubusercontent.com/16126044/90190340-71081c80-dd84-11ea-9be8-5781b38038d6.png">

**Comment by deborahjleslie** [comment]
Thanks, @ladylazarus3! I've been using Georgia as my preferred onscreen font for a long time, but find Lora particularly appealing. 

Since discovering Inconsolata a few hours ago, I've been playing around with different variations in a Word document. There are so many things to like about it: it's san serif with the exception of upper- and lowercase _eye_ and _jay_, and lowercase _ell_, so provides a nice visual relief between instruction text and examples. That it makes a clear distinction between zero and uppercase _oh_ is a nice plus. 

On the other hand, the examples demonstrate the awkward spacing associated with monospace. kalan, I think you used Inconsolata regular, yes? I'd like to see samples using ultracondensed varieties, adding medium and semibold weights for comparison.

Do I care passionately about typefaces, fonts, and general presentation. Why yes, I do. How did you know? (-;

**Comment by ladylazarus3** [comment]
@deborahjleslie Absolutely, i am grateful for this passion for typefaces, fonts, and general presentation.  :)  i think we are getting close! :)   i am including the CSS settings in the screenshots just so folks can see it along with the formatting itself.  The font-weight is added as a number (e.g. Medium = 500, Semibold = 600).  

This screenshot is Lora text with Inconsolata Ultracondensed Medium examples

![Lora text and Inconsolata Ultracondensed Medium examples](https://user-images.githubusercontent.com/16126044/90266900-58e2dc80-de1a-11ea-9d83-028aeabf8e86.jpg)

This screenshot is Lora text with the Inconsolata Ultracondensed Semibold examples

![Lora text and Inconsolata Ultracondensed Semibold examples](https://user-images.githubusercontent.com/16126044/90266910-5c766380-de1a-11ea-9714-732752de0f4a.jpg)

Any other tweaks needed?  Happy to try out other settings.  Once we narrow in a bit more, i'll sync the local changes to GitHub and send some screencaps of how it looks on my phone.  Thank you again for everyone's generous comments and sharing their gifts and keen eyes for typefaces, etc.! :)  

kalan

**Comment by flapka** [comment]
I agree that a font used must distinguish between an eye, ell, etc. So Helvetica fails.

To distinguish element names from example values, I wonder about:
1. Using small caps for the element names
2. Keeping element names and example values out of the same vertical space (though this might require more formatting than we want to implement)

Anyway, a picture to illustrate:
![image](https://user-images.githubusercontent.com/7634899/90275565-8175d100-de30-11ea-8b8a-e83f4ef3e4bc.png)

**Comment by deborahjleslie** [comment]
I like small caps for element names, and the layout Francis suggests--if it's not onerous to accomplish--is appealing. I'd like to see examples with wordier text. The chronogram example would do nicely. 

Do we really need to use the word "Example"? It adds extra white [grey] space, and quite frankly with the other obvious visual distinctions seems unnecessary. Especially when there's a disconnect with font size between the word itself and and the rest of the example text.

**Comment by deborahjleslie** [comment]
Oops, I already said my piece about the word "Example," and see that kalan's new examples omit it. What are others' thoughts?

**Comment by deborahjleslie** [comment]
I'm not so sure about Inconsolata after all. The exaggerated spacing between words creates a disturbing disjunction vis-a-vis the regular text.

**Comment by ladylazarus3** [comment]
Hi folks and many thanks especially @deborahjleslie and @flapka, i apologize in getting back to this so late.  The screenshot below is a combination of ideas.  Namely, for using small capitals for labels, tabular formatting within examples, and along with a san-serif font (Trebuchet MS).

i **really** like the use of small capitals for labels.  i'm not keen on the use of tabular formatting (and it would be a pain to accomplish) due to the fact the tables don't line up the cells properly.  Trebuchet MS seems to have some of the disambiguation in a san-serif that we require (but i mostly picked it because the name seems appropriate for a website on rare materials cataloging :) )
<img width="1415" alt="Lora and Trebuchet" src="https://user-images.githubusercontent.com/16126044/90451513-9dd47080-e0b1-11ea-8cc1-d2c95adbedcf.png">

Let's keep trying out ideas until we find one we like! :)  Thank you again to all for continually engaging this topic and issue,
kalan
.

**Comment by flapka** [comment]
Thanks @ladylazarus3 for your diligence and amazing work on this! Your example above reads well, I think; but if we're wary of nasty formatting requirements, it's certainly reasonable to entertain other possibilities.

**Comment by deborahjleslie** [comment]
We're getting closer, but the screenshot shows the eye/ell ambiguity. 

Like @flapka, I like the tabular format for clarity, but not worth maintaining if it's onerous or liable to breaking.

**Comment by deborahjleslie** [comment]
I keep bringing this up but there's been no direct response. I know that early in discussion on formatting examples, folks said they liked having the word "Example" precede the example, but that was before kalan developed the very distinct example formatting.  Are there strong feelings about keeping it?

**Comment by deborahjleslie** [comment]
The 'comment' line needs work. It's too small vis-a-vis the rest of the text, and the parens should be dropped.

**Comment by deborahjleslie** [comment]
I think I've got it: IBM Plex Sans, an open-source, sans serif font that distinguishes clearly between EYE, ell, and one. (I found it by googling "sans serif font distinguishable eye ell".) 

https://fonts.google.com/specimen/IBM+Plex+Sans?sidebar.open=true&selection.family=IBM+Plex+Sans#standard-styles

**Comment by ladylazarus3** [comment]
Hi folks,  
Thank you again, i agree-- i think we are really close.  Here is a screen capture of the chronogram example using IBMS Plex Sans.
![Lora, IBMS Plex Sans and small capitals](https://user-images.githubusercontent.com/16126044/90574920-c165ec80-e17f-11ea-8ff1-13bdf46babd0.jpg)  (i should have mentioned this earlier, but folks can click the screenshot while in the GitHub issue thread to open it in a new browser tab and make it bigger.)

The 'comment' line is much bigger.  It is a bit of a tricky compromise in the CSS to get this to correctly show up.  Ultimately, i used '*COMMENT*' in the same small capitals as the Element Labels.  i added the comment's text in sans serif.  Not ideal, but it does solve the problem of rendering much too small on the page while still being visually contained within the blockquotes.  

i know folks don't like the word "example" and i agree that it takes up a lot of real estate, but the idea behind including it was really to help out those who are using screen readers and for web accessibility best practices.  i (hopefully) will be taking some web accessibility classes soon and will reach out to our web accessibility folks at UMinn. once we kinda get this where we like it.  In this new formatting scheme, i think it takes up less real estate than before and like how it sets off the blockquote, but again, i'm not a web accessibility expert, by no means. :) 

Thank you, both, again so much.  i think we are really getting close.  That sans serif font sure does everything we need it to do.  IBM Plex Sans is an absolute stellar find! :)  Open source to boot! :)  Let me know if i  can try something else on for size or if folks are feeling pretty good about examples formatting at this point.

kalan

**Comment by elizhobart** [comment]
kalan, this looks great! Also agree with keeping the word "Example" for accessibility. It's going to be visually apparent that these blocks are examples to our sighted users, but we should make the standard usable for all our users.

**Comment by deborahjleslie** [comment]
It doesn't work to put the entire text of comments in small caps as was done for conversion of case: https://github.com/rbms-bsc/DCRMR/blob/9903edaf3e2fcc66685bc21f4677fae0d4ebcfb9/_pages/Edition/Statement-of-responsibility-relating-to-edition.md#3233-general-rule. Though I don't know if this represents the latest incarnation of example display.

**Comment by rarebkcat** [comment]
Hi, y'all--

Liz raised the issue Deborah mentioned above, about the comment text in examples being small caps; this was also mentioned in the Sept. 28 meeting. 

The short version is as Elizabeth summarized it: "Essentially, the “Example” label and the comments share a style. When “Example” was formatted as small caps, this affected all of the comments, as well. Styling them differently would require the Keepers to manually re-code every instance of comments in the text, which would be prohibitive."

The longer version: 

Think of each example having up to three components: 
* labels ("Example", "Element name", "Comment"; generally precedes a colon)
* example text proper (the text illustrating whatever we're talking about; transcribed or recorded as we would in a description)
* parenthetical text/comments (in parenthesis following the example text proper; generally labelled "Comment:" or "Source of information reads:")

Examples are formatted in the text by preceding them with a ">", which tells the website to format the text in a particular way. The example text proper is also wrapped in &lt;CITE&gt; tags; the labels and parenthetical text/comments are not. 

```
>Example:
>Element1 name: <CITE>Element1 text</CITE>
>Element2 name: <CITE>Element2 text</CITE>
>(*Comment*: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis.)
>(*Source of information reads*: Aliquam in porttitor leo, sit amet tristique arcu.)
```

I'm attaching the slide we shared at the Sept. 28 meeting about this as a .jpg.  It has the following components:
* The labels are "Example", "Date of publication", "Note on publication statement", and "Comment"
* The example text proper is "[1758]" and "Date of publication: derived from chronogram in statement of responsibility"
* The parenthetical text/comment is "Chronogram already transcribed ..."

Upthread, it was requested that labels be in small caps. kalan implemented this via CSS. However, the ramification is that the labels *and* the parenthetical text/comments in the examples are small caps; the example text proper isn't because it's wrapped in &lt;CITE&gt; tags. 

To echo was Elizabeth said in the email on the listserv, to have small caps labels and but not-small caps parenthetical text/comments would require us to manually wrap every single comment in &lt;CITE&gt; tags, which is prohibitive. 

kalan can speak more directly to the CSS (and, kalan, please elaborate if I've missed anything here!). However, the small caps can come out of of the CSS, as shown on the slide, it just means that they will also come out of the labels.

![CSS small caps for labels  - 4 205 4 3](https://user-images.githubusercontent.com/13946296/98592739-2709d680-22a0-11eb-830a-dfb224a47d8f.jpg)

**Comment by elizhobart** [comment]
I definitely don't want to ask to Keepers to manually edit every example. Since readability of comments is being affected by the small-caps, I this removing them may be our best best.

**Comment by ladylazarus3** [comment]
Hi folks,

Removing the CSS for small-caps takes about 30 seconds.  There are currently 135 examples with comments in the DCRMR text.  i can add 1/2 of the <CITE> tags globally.  The rest of the formatting would be coded by hand... which is probably going to take a couple of hours.  i love you all dearly and i want you all ecstatically happy with the appearance and contents of the final DCRMR text, but to me, a compromise might be removing the small-caps at this juncture, see if folks like it (or at least, get used to it), and revisiting our current decisions only if it is absolutely necessary.

Does that sound ok?  i'm happy to adjust the CSS (even just temporarily) on the current deployment if folks want to see what it looks like across the text as a whole.  Please let me know how i can help.

kalan

**Comment by lizoknj** [comment]
Sorry I missed out on this issue arising on the Fonts thread. 

I definitely don't want the Keepers doing hand-coding. If we can eliminate small caps in comments in a non-labor-intensive way, I would be in favor of that. Not quite sure what that would entail?

Liz

**Comment by ladylazarus3** [comment]
Hi folks,
i updated the CSS in the current deployment.  Here is a link to the [Chronograms example in 5.23.31.2](https://rbms-bsc.github.io/DCRMR/ppdm/Date-of-publication/#5.23.31.2).  What do folks think?

**Comment by lizoknj** [comment]
That looks fine to me, Kalan. Liz O'KeefeSent from my Galaxy
-------- Original message --------From: kkdavis <notifications@github.com> Date: 11/9/20  4:40 PM  (GMT-05:00) To: rbms-bsc/DCRMR <DCRMR@noreply.github.com> Cc: lizoknj <lokeefe411@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [rbms-bsc/DCRMR] Fonts (#54) 
Hi folks,
i updated the CSS in the current deployment.  Here is a link to the Chronograms example in 5.23.31.2.  What do folks think?

**Comment by io-uk** [comment]
Kalan, would you be able to change the CSS so that the labels are in bold? Just to see what it would look like and whether this would be preferable to what it currently looks like. (I realise that the comment would then be in bold, too). Obviously, only do this if it can be easily done in the CSS; I wouldn't want you to spend a lot of time on this.
Thanks.
Generally speaking, I think the normal font is better for readability than the small caps.

**Comment by elizhobart** [comment]
Thanks, kalan. I think this is more readable without the small-caps. I'll echo Iris's suggestion that we should find some other way to visually distinguish these, such as bolding or a font variant (I realize these are different fonts now, but I'm thinking maybe an even stronger difference). kalan, I actually experience with CSS. Would it be okay with you if I play with the style sheet to try a couple variations? I will revert it to the current state when I'm done.

**Comment by ladylazarus3** [comment]
i'm okay with folks trying out the css if @rarebkcat is.  The block quote css is in base.css and the documentation for the theme is in the minimal mistakes repo.   Feel free to contact me off thread with any questions.

**Comment by rarebkcat** [comment]
Thta's fine with me, @ladylazarus3 @elizhobart

**Comment by elizhobart** [comment]
Okay, I've done a little experimenting with font weight. Here's the current version:
![image](https://user-images.githubusercontent.com/65400653/98712561-76114380-2354-11eb-8bd0-c67646e79311.png)
Here's the same, with the example text bolded:
![image](https://user-images.githubusercontent.com/65400653/98712622-85908c80-2354-11eb-9ae1-72eaaebabddf.png)
And the same, with "Example" and comments bolded:
![image](https://user-images.githubusercontent.com/65400653/98712653-90e3b800-2354-11eb-8efa-454d8a5b9114.png)

Thoughts?

**Comment by deborahjleslie** [comment]
Hmm. Finding the variation in weights disconcerting, perhaps most by the entire comment in bold when the example isn't.

**Comment by deborahjleslie** [comment]
For maximum clarity: final decisions about typefaces have not yet been made, right?

**Comment by elizhobart** [comment]
@deborahjleslie that's correct; final decisions about typefaces have not been made (though anecdotally I did receive positive feedback about the current typefaces after the last BSC meeting). 

I'm fine with leaving the font-weight as is for the time being. Although some visual distinction might be useful, I also don't think it's difficult to parse as is.

**Comment by rarebkcat** [comment]
honestly, I'd just as soon leave everything as-is for now, with no smallcaps but also not playing with the font weight.

In general, I'd like everyone to have a chance to get used to everything before we make a lot of decisions. Having a website is a *very different* thing than having a book -- the flow is different, navigation is different, etc. Also, it's always hard to change, and getting used to new aesthetics, design, and navigation takes time! (Witness my refusal to update iTunes. Ever.)

Additionally, I know we'd also said, early on, that we were going to try to find an accessibility review; I think that should also factor in when we finalize how stuff looks.

**Comment by elizhobart** [comment]
I think @rarebkcat is right. We could be spending a lot of time trying to fix something that may not read as a problem to anyone else. Unless there's a true usage issue (such as the problem with "one," "ell," and "capital eye" being indistinguishable in chronograms), let's leave well enough alone for now.

Re: accessibility review: yes, we should pursue that. I'll be meeting with the BSC chairs sometime before the end of the year to discuss some of these big-picture issues. I will bring that up with them, especially since this is expertise we don't have within the editorial group.

**Comment by dcrmr** [comment]
I am going to close this (at least for now). We've had a lot of discussion on this issue. At this juncture, I'd like to get feedback from outside the editorial group before making additional changes to fonts.
