### ISSUE TITLE
Structured and unstructured note (Feb. 18, 2020) [from gdoc]

### ISSUE THREAD

**Issue by rarebkcat** [rbms-bsc/DCRMR#7]
In the  Post-3R Toolkit, the guidance chapter on recording methods “unstructured note” is given as an example of an [unstructured description](https://beta.rdatoolkit.org/en-US_ala-a06b3aa1-d994-31b1-b961-e4ce37c1a4d3/section_gvh_jsg_nbb) and “structured note” as an example of a [structured description](https://beta.rdatoolkit.org/en-US_ala-a06b3aa1-d994-31b1-b961-e4ce37c1a4d3/section_um2_x5h_tcb).  Would using “unstructured note” and “structured note” be more useful terminology to use within note element instructions versus structure and unstructured description?

See [Bound with](https://docs.google.com/document/d/1e_7vnfwA2xYCwypMM28V7ubDCbmAynExC9IFWGxbJRA/edit?usp=sharing) as an example where this issue arises.

**Comment by flapka** [comment]
Yes, I favor "structured note" and "unstructured note" where applicable.

**Comment by ladylazarus3** [comment]
i agree with Francis.  we could possibly include some of these terms in the Glossary.  That way a link for that term would resolve somewhere internal with our DCRM-ish definition.  i've started a tab to collect glossary terms in the Order of the Text spreadsheet.

**Comment by ladylazarus3** [comment]
if not the glossary, in the DCRM(B) introduction (in the pdf, see pages 19-20 in section VIII.2) there are some guidelines for notes and what they indicate.  This *might* be a good spot where additional instruction on unstructured and structured notes (what the differences are) can be added, if needed?

**Comment by ladylazarus3** [comment]
Here is the current deployment of the [Examples and notes page](https://rbms-bsc.github.io/DCRMR/books/introduction/Examples-and-notes/), since structured notes, unstructured notes, informal notes, and formal notes are going to appear in other chapters besides the [Other notes](https://rbms-bsc.github.io/DCRMR/other-notes/) and [Notes on items](https://rbms-bsc.github.io/DCRMR/notes-on-items/) chapters, it might make sense to put guidance on their usage in the prelims someplace.

**Comment by lizoknj** [comment]
Agree that it is much better to use structured note and unstructured note, since an unstructured description can take the form of a manifestation statement or an uncontrolled term, which aren’t what we mean by a note.
